### ISSUE TITLE
Short Dump due to Syntax Error

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#100]
![image](https://user-images.githubusercontent.com/7078215/91797082-0cdec700-ec65-11ea-95f0-b5c7804408f9.png)

Is there a minimum ABAP level needed to run the Code Pal checks?

I am on 7.50 / SP16

**Comment by hardyp** [comment]
IF_AUNIT_CONSTANTS is the interface in my system.

I fixed the code as follows: -

![image](https://user-images.githubusercontent.com/7078215/91797588-46640200-ec66-11ea-9a4b-b2790170cede.png)

**Comment by lucasborin** [comment]
Merged.
