### ISSUE TITLE
Another Syntax Error

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#103]
![image](https://user-images.githubusercontent.com/7078215/92044516-c5ba1880-edc1-11ea-8059-c44201f9b448.png)

![image](https://user-images.githubusercontent.com/7078215/92044545-d1a5da80-edc1-11ea-9d9a-6b0f8b7b4431.png)

What you should do is have a system on the lowest ABAP release the "Code Pal" is supposed to be compatible with and test it there before doing a new release.

**Comment by lucasborin** [comment]
Could you please validate the solution provided in the branch `fixing-basis-compatibility`?
