### ISSUE TITLE
Yet another syntax error

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#104]
![image](https://user-images.githubusercontent.com/7078215/92045053-f2bafb00-edc2-11ea-9705-8e7e3241f762.png)

![image](https://user-images.githubusercontent.com/7078215/92045102-12eaba00-edc3-11ea-86d3-78c58b28337e.png)

Cheersy Cheers

**Comment by lucasborin** [comment]
Could you please validate the solution provided in the branch `fixing-basis-compatibility`?

**Comment by hardyp** [comment]
I have looked at the proposed changes and they look good to me. I made equivalent changes to my system yesterday and all the syntax errors went away.
