### ISSUE TITLE
Syntax Error in Y_DEMO_FAILURES

### ISSUE THREAD

**Issue by abap-weasel** [SAP/code-pal-for-abap#106]
Actually, I am not even sure what this syntax errors means. Maybe even error in syntax check? Any suggestion?

![grafik](https://user-images.githubusercontent.com/47646214/92277298-e930b080-eef2-11ea-9ebf-e7d8f3c61660.png)

Ref system ABAP 7.40/SP0023.

**Comment by flaiker** [comment]
On 7.55 (?) you can now declare cx_no_check exceptions in signatures. They probably just removed the restriction completely so cx_root is also possible.
To downport just change it to cx_static_check.
