### ISSUE TITLE
Strange Error Message about Interfaces

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#108]
![image](https://user-images.githubusercontent.com/7078215/92292351-136c8780-ef60-11ea-882f-ae3845495c74.png)

There are no public methods in the code being checked, because it is a test class.

**Comment by lucasborin** [comment]
Hello @hardyp,

Are these methods `FOR TESTING` purpose?

I simulated it here, and I would say we should remove the `FOR TESTING` methods from the check. 
Do you agree?

![image](https://user-images.githubusercontent.com/5233413/92488644-364ba580-f1c5-11ea-8d34-14f4ef22810b.png)

Regards,
Lucas

**Comment by hardyp** [comment]
Yes that would make sense. A message like "0 public methods with interfaces" does not make any sense at all.

**Comment by lucasborin** [comment]
@hardyp: Could you please test the fix available in the linked pull-request?

**Comment by lucasborin** [comment]
By the way, could you please remove and re-add the check on your variant via SCI? 
We changed its default threshold from 0 to 1 a few weeks ago due to refactoring in the solution. We are sorry about it.

**Comment by hardyp** [comment]
It's all looking good now!
