### ISSUE TITLE
Number of Output Parameters

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#109]
![image](https://user-images.githubusercontent.com/7078215/92292376-46168000-ef60-11ea-862c-078fe3a53cf8.png)

![image](https://user-images.githubusercontent.com/7078215/92292392-60505e00-ef60-11ea-9247-ff66437d1a8b.png)

Even given that CHANGING counts as an EXPORTING parameter, surely one is not too many?

**Comment by lucasborin** [comment]
Helllo @hardyp, 

The `Y_CHECK_NUM_OUTPUT_PARAMETER` has a default threshold of 2, and it counts EXPORTING, CHANGING, and RETURNING as output parameters. Therefore, one single CHANGING parameter shouldn't be an issue.

![image](https://user-images.githubusercontent.com/5233413/92485876-d9022500-f1c1-11ea-9982-364b76214d65.png)

Furthermore, I simulated the example method you sent, and the `Y_CHECK_NUM_OUTPUT_PARAMETER` wasn't raised:

![image](https://user-images.githubusercontent.com/5233413/92485733-b243ee80-f1c1-11ea-972c-e7a1c677e49f.png)

![image](https://user-images.githubusercontent.com/5233413/92485769-be2fb080-f1c1-11ea-885e-024a3154038a.png)

Is there any additional parameter in the method?

Regards,
Lucas

**Comment by hardyp** [comment]
I just ran the Code Inspector checks again. Yesterday the result was as in my screen shot.  I switched the "output parameters" check off in SCI, and then switched it back on again. Now the error does not appear. So this issue can be closed.
