### ISSUE TITLE
Runtime Error STRING_LENGTH_TOO_LARGE in Y_CHECK_COMMENT_POSITION->IS_PSEUDO_COMMENT

### ISSUE THREAD

**Issue by justrockstar** [SAP/code-pal-for-abap#127]
[Dump.pdf](https://github.com/SAP/code-pal-for-abap/files/5212497/Dump.pdf)
Dear guys,
Thank you for PAL, great idea! I tried the checks on an NW 750 SP 16 (09/2019).

The Comment Check stops with a runtime error STRING_LENGTH_TOO_LARGE in method Y_CHECK_COMMENT_POSITION->IS_PSEUDO_COMMENT. If you like, we can do screensharing.
Dump attached.

Thanks,
justrockstar

**Comment by lucasborin** [comment]
```
METHOD is_pseudo_comment.
   result = COND #( WHEN token-str(4) = '"#EC' THEN abap_true ).
ENDMETHOD. 
```

```
TOKEN-STR 
"no 
```

We have to check if `token-str` has at least 4 positions.
