### ISSUE TITLE
Big Change - Change Naming of Packages & Check Category

### ISSUE THREAD

**Issue by eugen-guenther-sap** [SAP/code-pal-for-abap#134]

**Comment by abap-weasel** [comment]
This will resolve #55, right?

**Comment by lucasborin** [comment]
Yes, it will as it will convert the project to use the `PREFIX` mode.

**Comment by lucasborin** [comment]
If you want to test it, first, you have to uninstall the code-pal-for-abap from your system using abapGit, and then clone the project again using the `changing-from-full-to-prefix` branch instead. The installation step-by-step is available in the README.md on this branch.

**Comment by lucasborin** [comment]
Bu the way, I will close this issue as it is Duplicated #55 as you mentioned. Let's follow in #55 instead.
