### ISSUE TITLE
Extend Magic number checks for numeric strings

### ISSUE THREAD

**Issue by smb** [SAP/code-pal-for-abap#142]
https://github.com/SAP/code-pal-for-abap/blob/master/clean_code_main/clean_code_checks/y_check_magic_number.clas.abap
https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/magic-number.md

Could this be extended to also detect something like

`IF my_variable = '5'.` ?

Something like this in the check:

`^(?!'?[01]'?$)\'?\d+\'?$` 

(Could also create a PR if needed - The negative lookahead for 0 / 1 doesn't improve readability of this regexp)

https://regex101.com/r/MwfLLJ/2

**Comment by lucasborin** [comment]
It will be part of the v.1.04.1.
