### ISSUE TITLE
What is the reason for check parameter "Message severity"?

### ISSUE THREAD

**Issue by ThomasKempfle** [SAP/code-pal-for-abap#143]
All Code Pal checks provide a parameter for "Message severity". However, the severity of ATC messages can be defined inside transaction SCI "Management of message priorities". Hence no other ATC checks seem to provide a parameter for that. Therefore I want to recommend  to remove the parameter "Message severity" from the base class Y_CHECK_BASE and instead define the severity in the same way, as for the other check classes.

**Comment by flaiker** [comment]
The severity in SCI is at system level it think while the custom ones can be set for each check variant.

**Comment by lucasborin** [comment]
Hi Thomas,

Our tool was created based on the SCI (Code Inspector), and you can integrate it with ATC if you set the user parameter SATC_CI_MODE in your user profile (via transaction SU3). On the other hand, SCI doesn't allow the severity customization. Therefore, we implemented it for users which use Code Inspector. 

Regards,
Lucas

**Comment by ThomasKempfle** [comment]
I don't really get it: SCI **DOES** allow to control the severity level of any given check message. 
_Transaction SCI > Code Inspector > Management of > Message priorities_
Here I can define for any given check, what kind of message type it will produce (info, warning, error). This overrides every message type defined in the check.
That's why I think the "Message severity" parameter is superfluous in the Code Pal.

**Comment by lucasborin** [comment]
Hm, I see. Yes, you can use the Code Inspector to set the priorities as you mentioned. However, you can set only one priority for each check for the whole system. On the other hand, the code pal for ABAP, thru the Profiles feature, allows teams or organizations to create distinct priorities for each check (+thresholds, +validity, etc) in the same system.

**Comment by ThomasKempfle** [comment]
Ah, understood: By this you could accept certain code smells for one application but forbid this in another application. Since this has been sorted out, I will close the issue,
