### ISSUE TITLE
Redundancy of check classes

### ISSUE THREAD

**Issue by ThomasKempfle** [SAP/code-pal-for-abap#144]
I noticed, that several Code Pal checks are already covered from SAP standard checks. E.g. the Code Pal checks
"_Number of attributes_", "_Number of methods_", "_Number of public Attributes_" is already integrated in the SAP standard check class "_OO Size metrices_". The Code Pal check "_Nesting depth_" is included in the SAP standard check "_Program complexity Test_" and so on.
What is the reason for that? 
Users of Code Pal and SAP standard checks have to consider, which one of the checks is the better or more accurate one. If both checks are activated at the same time, they might produce redundant or even contradictory messages and the repository of the system (superfluously) increased.
My recommendation would be, to remove any check classes from the Code Pal, that is already covered from the SAP standard.

**Comment by lucasborin** [comment]
Hi @ThomasKempfle,

Unfortunately, the code pal for ABAP is not a standard tool provided by SAP. 
This is an open-source project.

The reason why it has some "duplicated" checks is that in code pal for ABAP: 
1. You can filter by object creation date;
2. You can choose between productive and test code;
3. It excludes most of the generated code automatically;
4. You can use the profile tool to customize the checks and export/import the configuration between systems.
5. etc.

Besides, it is up to the user to decide if he/she wants to use the code pal for ABAP checks or the SAP standard ones. 

Regards,
Lucas & Eugen

**Comment by estevao-schultz-neto-SAP** [comment]
Besides, code pal was newly developed with A better (not to say state-of-the-art) OO Programming. What is not the case regarding these old checks you have mentioned.

**Comment by ThomasKempfle** [comment]
Thank you for this information. Can anybody tell me, if the Code Pal checks will somehow become reflected to the SAP standard?

**Comment by lucasborin** [comment]
Code pal for ABAP started in SAP (internally) by some developers to support internal team needs, and we figured out that would be helpful for people out of SAP. Therefore, we converted it into an open-source project, so everyone can use, improve, and support it. Currently, **this is not an official SAP tool** or replacement for code inspector tool.

**Comment by estevao-schultz-neto-SAP** [comment]
Enhancing, code pal for ABAP is a initially developed by SAP and placed in the [SAP Open Source Developer Hub]((https://developers.sap.com/open-source.html)). Although no official SAP Support (e.g.: translation) is offered for the tool, we are coordinating it and further developing it together with the OS Community.
