### ISSUE TITLE
Check for class-based exception does not work correctly

### ISSUE THREAD

**Issue by macemmi** [SAP/code-pal-for-abap#154]
We have many findings because of code like this:

    IF sy-subrc <> 0.
      RAISE EXCEPTION cx_my_exception_class=>create_from_symsg( ).
    ENDIF.

Here the check will issue a finding even though class based exceptions are used.

BR

**Comment by lucasborin** [comment]
Raise statement syntax: https://syntax.abaplint.org/#/statement/Raise

**Comment by macemmi** [comment]
I don't get your point. Do you want to tell me that the raise statement above is not correct and should lead to a syntax error? This is not the case, it works and we use it (as said) in many places.

**Comment by lucasborin** [comment]
No, I am sorry. I did not mean your code is wrong. I just linked the raise syntax to support the issue analysis.
