### ISSUE TITLE
CHECK statement position findings are sometimes not correct

### ISSUE THREAD

**Issue by macemmi** [SAP/code-pal-for-abap#155]
We also get findings for CHECK statements occuring in a LOOP like

    LOOP AT lt_components INTO DATA(ls_component).
      CHECK ls_component-name <> 'YXZ'. 

From the documentation, CHECK should only be checked on method level.

**Comment by lucasborin** [comment]
Following the [Style Guide for Clean ABAP](https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#avoid-check-in-other-positions):

>For example, CHECK in a LOOP ends the current iteration and proceeds with the next one; people might accidentally expect it to end the method or exit the loop. **Prefer using an IF statement in combination with CONTINUE instead, since CONTINUE only can be used in loops**.  

I agree with the current behavior of the check to report the CHECK inside of LOOP.
