### ISSUE TITLE
Number of public attributes threshold

### ISSUE THREAD

**Issue by jrodriguez-rc** [SAP/code-pal-for-abap#158]
Number of public attributes check has no threshold option
![image](https://user-images.githubusercontent.com/56556686/94701817-60643380-033d-11eb-9361-0b5b4cfdb691.png)

In code is setted to 1
![image](https://user-images.githubusercontent.com/56556686/94701919-7a057b00-033d-11eb-856a-9a588f90a8fd.png)

But the check is raising even if no public attributes exists
![image](https://user-images.githubusercontent.com/56556686/94702271-d9638b00-033d-11eb-87da-f266ee297024.png)

**Comment by lucasborin** [comment]
We recently changed its default threshold from 00 to 01 to keep its threshold behavior like the other checks (once you have one public attribute, raise the error), and to support the new unit test framework.

Are you using the Profiles feature? 

If so, I kindly ask you to remove the check from the profile and assign it again (it will use the new default threshold).

If you are not using the Profile, could you please deactivate the Check in the SCI framework, and reactivate it?
1. T.code SCI > Code Inspector > Mangement Of > Check > Unselect `y_check_num_public_attributes` > Save;
2. T.code SCI > Code Inspector > Mangement Of > Check > Select `y_check_num_public_attributes` > Save. 

Let me know if it works, or if you need new further support on it.

**Comment by jrodriguez-rc** [comment]
I'm executing it without Profile, just SCI configuration.

I tried to unselect > save > select > save and still I get the error.

Including configuration in Profile works fine, but I need to apply only in a specific SCI variant

**Comment by lucasborin** [comment]
Hm, interesting. It looks like something in a buffer because it works with the Profile feature. 
Have you tried to unselect > save > select > save the Check in the SCI variant?

**Comment by jrodriguez-rc** [comment]
Yes, I tried it from Mangement Of > Check and directly in the variant.

It's like the variant settings saved threshold 0 from the initial configuration.

Is there any way to restore default settings only for a check in a variant?

**Comment by lucasborin** [comment]
Yeah, it looks the variant saved the threshold 0. We will take a deeper look at it.

I have a workaround to suggest to you: 
1. Open the `y_check_num_public_attributes`, and change the `settings-disable_threshold_selection` to `abap_false` in the class constructor;
2. Go to `SCI` and unselect > save > select > save the check via Management Of > Check;
3. Go to `SCI` and change the set threshold from 0 to 1;
4. Rever the changes (1~3 having `disable_threshold_selection` it as `abap_true`).

**Comment by jrodriguez-rc** [comment]
It is working with this change, thanks
