### ISSUE TITLE
Read Table into a Field Symbol

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#177]
I did a check and got the warning that I should not assign a table rows unless I want to change that row.
![image](https://user-images.githubusercontent.com/7078215/96318968-1e383300-105b-11eb-83f3-8f046594506b.png)

I then check the code and find that the entire purpose of reading the rows into a field symbol was to change a value.
![image](https://user-images.githubusercontent.com/7078215/96319346-3a3bd480-105b-11eb-8d43-572972c6144e.png)

I presume the check looks at the field symbol to see if any values are getting changed? If so, it is not working.

**Comment by eugen-guenther-sap** [comment]
Hello @hardyp,
The check seems to work like intended but the documentation was not updated so far.
This checks searches for the reuse of a FIELD-SYMBOL in another READ TABLE.

Without seeing the complete code its hard to validate if its a problem but if you see still an issue, just let us know.

**Comment by hardyp** [comment]
After reading the documentation six times I finally understand what the check is for. If you read row 1 of the table into field symbol <LS_ROW> using the ASSIGNING mechanism the field symbol point to the first row of the table.
If you then do READ ITAB INTO <LS_ROW> INDEX 2 that will cause the first row of the table to be over-written with the second row of the table. The developer may think that the field symbol is pointing to the second row.
However if you use READ ITAB ASSIGNING <LS_ROW> INDEX 2 then the first row is unchanged, and the field symbol will point to the second row.
That is a good check to do.
In my specific case at no point to I use the INTO variant, always the ASSIGNING variant. Therefore I think the check is returning a false positive.

Cheersy Cheers

Paul

**Comment by lucasborin** [comment]
Could you please import the `fixing-subsequent-readtable` branch and check if the false-positive is removed?

**Comment by hardyp** [comment]
Yes, that fixed the problem.
