### ISSUE TITLE
RECEIVING Usage Check in BAdI

### ISSUE THREAD

**Issue by jrodriguez-rc** [SAP/code-pal-for-abap#18]
Calling a BAdI Receiving statement should be specified, but checks throw a message
![image](https://user-images.githubusercontent.com/56556686/81924115-f4c43880-95de-11ea-90eb-eb0ddfbc9f71.png)

**Comment by estevao-schultz-neto-SAP** [comment]
Hello Rodriguez,

**Comment by estevao-schultz-neto-SAP** [comment]
hello jrodriguez-rc,

Thanks for using and actively contributing to the community! 
According to the SAP ABAP Styleguides, RECEIVING should be omited (whenever possible) encouraging dynamic calls:

**Comment by jrodriguez-rc** [comment]
Hello, so in BAdI interfaces the recommendation is to use EXPORTING instead of RECEIVING?

**Comment by estevao-schultz-neto-SAP** [comment]
Hi jrodriguez-rc, 

There is no such recommendation. However, there is a clear recommendation for dynamic calls (avoiding words like: EXPORTING, IMPORTING, RETURNING, RECEIVING, CHANGING, etc...). My question was: If this could be your case (omitting such wordings)? 

TRY
   rs_info = lb_badi->get_info ( lv_title, lv_use_graph, mt_param).
CATCH...
ENDTRY.

**Comment by jrodriguez-rc** [comment]
Hi @estevao-schultz-neto-SAP,

It is not possible to call a BAdI method directly:
![image](https://user-images.githubusercontent.com/56556686/82252851-12333280-9950-11ea-917c-b2e3b900dc81.png)

This is the reason because I need to specify keywords when calling a BAdI method
![image](https://user-images.githubusercontent.com/56556686/82252877-26772f80-9950-11ea-9adb-dc016ac6a1dc.png)

**Comment by estevao-schultz-neto-SAP** [comment]
Yes, CALL BADI is needed (in order to explicitly show that a BAdI is being called). Our colleagues from SAP BASIS informed they are about to change that in a near future so that CALL BADI would follow 100% the CALL METHOD possibilities (including dynamic calls). For that reason, we will introduce the acceptance of this keyword (RECEIVING) for the specific case of CALL BADI. 
Thank you for reporting this issue :-)

**Comment by jrodriguez-rc** [comment]
Thank you!
I don't know when I can see it, depending on the version in which it could be implemented (healthcare is still in 7.50)

**Comment by estevao-schultz-neto-SAP** [comment]
Changes will be done directly in our repository (github). Then you can pull it again. We'll let you know as soon as it's implemented.

**Comment by jrodriguez-rc** [comment]
I mean about calling a BAdI method same as a class method

**Comment by estevao-schultz-neto-SAP** [comment]
This implementation does not rely on our team. Unfortunately I cannot give any concrete statement.

**Comment by eugen-guenther-sap** [comment]
for the time beeing we exclude it from the check.
