### ISSUE TITLE
Yet another syntax error

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#187]
![image](https://user-images.githubusercontent.com/7078215/97126382-c00dfd00-178a-11eb-99c1-b770e59b68d6.png)

![image](https://user-images.githubusercontent.com/7078215/97126424-e338ac80-178a-11eb-982e-ca677c73075a.png)

These syntax errors happen with alarming frequency. It is getting to the stage where it is too dangerous to download a new version of "Code Pal" from GitHub....

**Comment by larshp** [comment]
@hardyp you can always install the previous version again(assuming there are no changes to database tables)

@code pal: would you be interested in a pull request with an abaplint configuration? It should be possible to find most of the syntax errors by running abaplint on all pull requests

**Comment by lucasborin** [comment]
I'll check if it is possible to install the application in the repository. Otherwise, we will check the other options. By the way, I approved the pull-request.
