### ISSUE TITLE
'might' as prefix for boolean return methods

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#197]
![image](https://user-images.githubusercontent.com/5233413/97584681-0a83b980-19d7-11eb-8bda-ee5cf0e6a293.png)

![image](https://user-images.githubusercontent.com/5233413/97584636-fcce3400-19d6-11eb-8f3c-86bc6411da35.png)

False-positive?

**Comment by estevao-schultz-neto-SAP** [comment]
I even don't understand this naming... Too confusing! I would rather write: DATA(is_unpredictable)... DATA(is_inconsistent)...
