### ISSUE TITLE
Review Checks in Test Code

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#198]
![image](https://user-images.githubusercontent.com/5233413/97588922-baf3bc80-19db-11eb-886b-b3f2fbd5d8c7.png)

![image](https://user-images.githubusercontent.com/5233413/97588990-ca730580-19db-11eb-8163-b33bc6d513ac.png)

Should we implement interfaces in local double classes?

**Comment by lucasborin** [comment]
Let's deactivate this check from the test code, and let's check other similar checks.

**Comment by estevao-schultz-neto-SAP** [comment]
the other checks that need to be verified would be all: *number_of_* (but let's keep it simple), I will revert the name of this issue to the original (narrow it down to the removal only for LTCs).

**Comment by estevao-schultz-neto-SAP** [comment]
In fact, I would like to change the name of this CHECK to: Y_CHECK_INTERFACE_MISSING and so the pseudo-comment: #EC INTF_MISS; feasible or too late? Someone raise an issue on that.

**Comment by lucasborin** [comment]
I think it is fine. However, I would keep both checks in the tool for a while (maybe, 1 month) asking the user to migrate to the new one as the former will be removed soon. 

There are a few migrations required (if it is in use): 
1. SCI variant customizing;
2. Pseudo comments in code;
3. Check customizing in Profiles feature.

Therefore, I would:
1. Duplicate the check using the new name and pseudo comment;
2. Change the former check message and description to have a `[deprecated]` tag on it;
3. Create and describe a new [how-to-migrate ](https://github.com/SAP/code-pal-for-abap/blob/master/pages/how-to-migrate.md) with a step-by-step.
