### ISSUE TITLE
Wrong URL in Documentation

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#2]
The URL on the screenshot doesn't work (at least for me)

I used https://github.com/SAP/code-pal-for-abap instead and all was fine.

**Comment by larshp** [comment]
fixed in https://github.com/SAP/code-pal-for-abap/pull/1 ?

**Comment by hardyp** [comment]
Yes when that gets merged the problem will be fixed. I did not notice the pull request.
