### ISSUE TITLE
Tool Failure Y_CHECK_COMMENT_POSITION

### ISSUE THREAD

**Issue by abap-weasel** [SAP/code-pal-for-abap#203]
I have the following tool failure. Issue comes up in a function group, but I cannot see exactly what is the code / routine that has the error as only the complete function group itself is shown as issue. 

![image](https://user-images.githubusercontent.com/47646214/97982319-e576b880-1dd3-11eb-819a-cb11062e3dcf.png)

Can you provide a fix from that screenshot alone or do you need further details (if so, which?)?

Edit: 
English Translation of the German text is "Description: A row with the index 91 is not in the table."

**Comment by abap-weasel** [comment]
@lucasborin: I think this issue was closed without merging the fix to master branch. Can you check that, please?

**Comment by lucasborin** [comment]
@abap-weasel: We haven't released it yet because we are still working on some major reported issues, and we want to run some regression tests. On the other hand, you can use the beta branch (1.07.0) until we release it officially. Hopefully, we will release it next week.
