### ISSUE TITLE
Y_CHECK_NUM_OUTPUT_PARAMETER: Error message should be adjusted

### ISSUE THREAD

**Issue by estevao-schultz-neto-SAP** [SAP/code-pal-for-abap#208]
Since there is actually no need of a THRESHOLD for this check (it is always 1), there is no need to have the error message in this way: "2 output parameters reaching the threshold of 2".

Instead, the error message could be:
"Only 1 output parameter is allowed"  OR
"2 Output parameters exceeding the threshold of 1".

Let's try to have a consistency with the other checks checking a "number of" (statements, attributes, events, etc...).

**Comment by lucasborin** [comment]
I vote on the first option: 
-> "Only X output parameter(s) is allowed!"

**Comment by estevao-schultz-neto-SAP** [comment]
> I vote on the first option:
> -> "Only X output parameter(s) is allowed!"

me too.

**Comment by lucasborin** [comment]
Or, it could say: 'Number of output parameters must be lower than X".
Otherwise, to use the 'Only X output parameters is allowed', we will have to change the threshold validation (currently >= or <=).

**Comment by estevao-schultz-neto-SAP** [comment]
'Number of output parameters must be lower than X". ---> **this is okay.**
