### ISSUE TITLE
Y_CHECK_RETURNING_NAME attribute values need to be adjusted

### ISSUE THREAD

**Issue by estevao-schultz-neto-SAP** [SAP/code-pal-for-abap#209]
- Y_CHECK_RETURNING_NAME:
Check should be a W (Warning) instead of an E (Error) in the default delivered values.
Y_CODE_PAL default values need to be adjusted.

**Comment by lucasborin** [comment]
The default error level is set in the check base, and it is Error. Should it be a warning as well?

**Comment by estevao-schultz-neto-SAP** [comment]
yes, as W also in the base.

**Comment by lucasborin** [comment]
We won't change the default value.
