### ISSUE TITLE
No Y_CODE_PAL profile after intallation

### ISSUE THREAD

**Issue by ThePlenkov** [SAP/code-pal-for-abap#210]
Hi! 

I'm trying to explore this project and just following the configuration guide. 

However when I try to execute - I do not see any Y_CODE_PAL profile in ATC. 

What do I do wrong? thank you!

**Comment by lucasborin** [comment]
Hey, welcome!

Have you created the variant in the SCI transaction? If not, you just have to create a variant and select the respective checks from code pal. 

It is mentioned here (item 3):
https://github.com/SAP/code-pal-for-abap/blob/master/pages/how-to-install.md

Let me know if you need any further support on it.

**Comment by ThePlenkov** [comment]
Hi! I realized now how it works. Really cool! I didn't know is possible to write such checks so easily. Thanks!
