### ISSUE TITLE
Prefer IS NOT to NOT IS

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#219]
Feedback received:
> we get this message for the code "IF NOT line_exists( … )", but I am not aware of a "line_does_not_exist" function. The message should, of course, only appear if there really is a "IS NOT"-style alternative to the code, and not just check whether the condition starts with "IF NOT"

**Comment by lucasborin** [comment]
Should we exempt the line_exists only? Do we have any other better approach?

**Comment by lucasborin** [comment]
@estevao-schultz-neto-SAP: Any idea?

**Comment by lucasborin** [comment]
line_exists exempted.

**Comment by estevao-schultz-neto-SAP** [comment]
Let's check it together!!
