### ISSUE TITLE
CL_AUNIT_ASSERT usage in code-pal

### ISSUE THREAD

**Issue by larshp** [SAP/code-pal-for-abap#236]
Hi,
according to https://help.sap.com/doc/saphelp_nw75/7.5.5/en-US/4e/c2efe26e391014adc9fffe4e204223/content.htm usage of CL_AUNIT_ASSERT is obsolete, I dont think it has any special features over CL_ABAP_UNIT_ASSERT ?

https://github.com/SAP/code-pal-for-abap/search?q=CL_AUNIT_ASSERT

**Comment by lucasborin** [comment]
How about if we create a check to search for it? (@SAP/code-pal-for-abap-admin)

**Comment by estevao-schultz-neto-SAP** [comment]
Nice idea! But I think we will have the same known problem as in Y_CHECK_DB_ACCESS_IN_UT when the "failure" is not directly in the examined code (but encapsulated inside of a another call). There are also some frameworks used which do not have the ASSERT directly in the examined/parsed object but where else modularized/encapsulated. Got my point?

**Comment by lucasborin** [comment]
Hm, I see. We can configure the check to run in the test and non-test code, so it covers all the objects. It is a simple read table in the tokens searching for the class name (CL_AUNIT_ASSERT).

**Comment by lucasborin** [comment]
`if_Aunit_Constants` is also deprecated, and we should we `IF_ABAP_UNIT_CONSTANT` instead

**Comment by estevao-schultz-neto-SAP** [comment]
isso seria ENHANCEMENT ou NEW CHECK ?

**Comment by lucasborin** [comment]
Both:
- ENHANCEMENT (see pull request #238) to change the deprecated interface and class in the code-pal source;
- NEW CHECK to enhance code-pal scope.

**Comment by lucasborin** [comment]
Ps: IF_ABAP_UNIT_CONSTANT does not exist in ABAP 7.40
