### ISSUE TITLE
Running code pal for ABAP with user parameter SATC_CI_MODE set to "X".

### ISSUE THREAD

**Issue by estevao-schultz-neto-SAP** [SAP/code-pal-for-abap#242]
**PROBLEM:** (problem described by one of our users):
For Code Pal, we have to set user parameter SATC_CI_MODE to X. However, this seems to cause conflict when looking up ATC issues from our consolidations system. Is it a known issue? How should we deal with that so that both Code Pal and proper ATC issues show up in our dev system?

**SOLUTION**
Setting this user parameter SATC_CI_MODE = X means that the Code Inspector Mode is activated,
Furthermore, it means you have to use then "Code Inspector" and catching the results via ATC is no longer possible.
One has to decide: The parameter is a switch between working with CI or ATC (for getting the results).

Maybe we need do discuss all possible ways of executing the code pal:
1. Via SCI and SCII with a variant or profile;
2. Via job (API) with a variant or profile;
3. Via SUT with CI Flavour with a variant or profile;
4. Via ADT/WBT (e.g. SE80 or Eclipse) **--> here one needs the above mentioned flag**.

**Comment by DerGuteWolf** [comment]
I definitly miss sone guidance what to use here. We have a central ATC check system established and check our code via ADT/AiE from the development systems with the help of several remote check variants. Results are consumed in ADT/AiE.
I want now add a possibility to do code-pal checks from ADT/AiE and also consuming results in ADT/AiE.
As I understand the above the setting  SATC_CI_MODE = X will disturb our currenct procedure?

**Comment by lucasborin** [comment]
> I definitly miss some guidance what to use here.
> We have a central ATC check system established and check our code via ADT/AiE from the development systems with the help of several remote check variants. Results are consumed in ADT/AiE.
> I want now add a possibility to do code-pal checks from ADT/AiE and also consuming results in ADT/AiE.
> As I understand the above the setting SATC_CI_MODE = X will disturb our currenct procedure?

It basically changes the ATC mode from CHECKMAN to CODE INSPECTOR.

For instance, if you call the `Run As > ABAP Test Cockpit With...` via ADT:
1. and the flag is set (X): Then you activated the CODE INSPECTOR mode and you can enter the variant that triggers the code pal (usually, Y_CODE_PAL);
2. and the flag is not set (''): Then you activated the CHECKMAN mode and you can call its variant (usually, the default for ATCs, `ZDLM_<sy-sysid>`)

Unfortunately, we haven't found a way to run both simultaneously yet. :(

Ps: If you are an SAP employee, you can use the SUT framework in the SAP systems to inspect the code. It allows you to set the ATC mode on each execution with no dependency on the user flag.

**Comment by lucasborin** [comment]
Technically, it is the way that the ATC tool works. You can choose between CHECKMAN and CODE INSPECTOR. As code pal is a tool that uses the CODE INSPECTOR as its framework, it depends on this customizing.

**Comment by D072189** [comment]
SATC_CI_MODE is a parameter that is only relevant in certain SAP-internal systems. As an open tool, this tool should not do anything specific for SAP-internal system - the internal systems need to use ATC in CI mode by default if they want to use this like everyone else. The "CHECKMAN" choice has never been delivered outside of SAP.

**Comment by DerGuteWolf** [comment]
@D072189 so step 4 of the how-to-install.md does not need to be done outside of SAP, right? Anything else which is different from the current how-to guides outside of SAP?

**Comment by D072189** [comment]
Indeed, step 4 is not necessary in non-SAP systems (and really should never have been part of public-facing documentation). We'll have to review the rest of documentation for more things of this kind (tracked now in #557), but I haven't seen any at a first glance
