### ISSUE TITLE
Clean Exporting Parameters

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#263]
I am not sure why, but some colleagues are cleaning the exporting parameters at the start of the method. 
Since it is not necessary, I consider it dirty.

How about creating a new check to catch it?

**Comment by abap-weasel** [comment]
According to Clean Code Guide it is actually recommended to clear exporting parameters. 
"**Generally, it is a good idea to clear the parameter as a first thing in the method** after type and data declarations. This makes the statement easy to spot and avoids that the still-contained value is accidentally used by later statements."
→ see https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#clear-or-overwrite-exporting-reference-parameters

=> So a new check should actually check that clear is performed?!

**Comment by lucasborin** [comment]
Yeah, I agree with you @abap-weasel and CleanABAP. Thanks for your contribution.
