### ISSUE TITLE
Y_CHECK_DB_ACCESS_IN_UT: Check for cl_sql_statement

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#269]
![image](https://user-images.githubusercontent.com/5233413/101175929-8bf8e800-3624-11eb-9fb2-c32bc4967161.png)

Source: 
https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abapexec.htm#:~:text=EXEC%20SQL.&text=ENDEXEC.,statements%20can%20be%20specified%20statically.&text=Almost%20all%20SQL%20statements%20that,in%20particular%20the%20DDL%20statements.

**Comment by D072189** [comment]
This doesn't currently appear to be part of the [style guide](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md), but in any case, there already exists an ATC check that finds all uses of EXEC SQL: The "Critical Statements" check (CL_CI_TEST_CRITICAL_STATEMENTS, when "native SQL" is checked in the options). There's no need to duplicate such a check.
