### ISSUE TITLE
Y_CHECK_STATEMENT_POSITION: before DATA declarations?

### ISSUE THREAD

**Issue by estevao-schultz-neto-SAP** [SAP/code-pal-for-abap#272]
REPORTED:  CHECK keyword is expected to be put even before DATA / FIELD-SYMBOL declaration lines. Why? Those are not executable, and it would feel weird to look for executable code up there.

**Comment by estevao-schultz-neto-SAP** [comment]
This was reported by an internal colleague (SAP Intern). I agree with him. CHECK may be placed after DATA / FIELD-SYSMBOLS declaration.

**Comment by lucasborin** [comment]
How about inline declarations?

IMO, OK:
```
DATA age TYPE i.
age = class->get_age( ).
IF age IS INITIAL.
  RETURN.
ENDIF.
...
```

IMO, NOT OK:
```
DATA(age) = class->get_age( ).
CHECK name IS NOT INITIAL.
...
```

**Comment by estevao-schultz-neto-SAP** [comment]
But if the data declaration is dynamic, the CHECK has to be before it.

**Comment by estevao-schultz-neto-SAP** [comment]
The only thing we will allow before it is DATA / FIELD-SYMBOLS (non dynamic declarations) and CLEAR.

**Comment by lucasborin** [comment]
By the way, the dynamic/inline declaration is allowed (unit test):

![image](https://user-images.githubusercontent.com/5233413/101353835-061eac00-3873-11eb-934b-5a78b72ab8db.png)

**Comment by lucasborin** [comment]
CLEAR then CHECK will not be allowed as we have not found any reason for it. If someone uses it, please let us know.
