### ISSUE TITLE
Scope of the Variable

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#276]
Feedback received:

> ABAP lacks proper scope handling. So the `DECLARATION IN IF ` check should be adjusted in order to check the scope. If a variable is declared in an IF-Block, it should only be used/referred to inside this IF-block (not outside). The same applies to LOOP, DO, WHILE, or any block structure. Thus, we can still make usage of dynamic declarations inside of blocks with a single statement:
> 
> ```
> IF cond = abap_true.
>   DATA(var) = get_method().
> ELSE.
>   var = 'C'. "no longer accepted
> ENDIF.
> 
> var = 'B'. "no longer accepted
> ```
> 
> Perhaps we should downgrade this check from ERROR to WARNING just to make it a common practice first :-)

**Comment by lucasborin** [comment]
Should we rename it? 

1. Y_CHECK_SCOPE_OF_VARIABLE
2. Y_CHECK_VAR_OUT_OF_DECL_SCOPE
3. Y_CHECK_USAGE_OUTSIDE_DECL_SCOPE
4. Y_CHECK_WRONG_SCOPE_VAR_DECL

@SAP/code-pal-for-abap-admin : Please, vote. :)

**Comment by lucasborin** [comment]
My vote is for (1).

**Comment by estevao-schultz-neto-SAP** [comment]
Our CHECK checks the scope of a VAR. By the way, we call them variables but in OOP, variables are actually called attributes. A class has global attributes. A method has member attributes. But anyway, I think (1)  reflects what the check does:
Y_CHECK_SCOPE_OF_VARIABLE  (or even Y_CHECK_SCOPE_OF_ATTRIBUTE).

**Comment by lucasborin** [comment]
Keep in mind it includes FIELD-SYMBOLS as well. I am also not sure if 'variable' is a good name...

**Comment by estevao-schultz-neto-SAP** [comment]
I would see in this case a FIELD-SYMBOL declaration as a "variable".
