### ISSUE TITLE
Cognitive Complexity

### ISSUE THREAD

**Issue by estevao-schultz-neto-SAP** [SAP/code-pal-for-abap#279]
New check to be developed:
https://docs.codeclimate.com/docs/cognitive-complexity

**Comment by estevao-schultz-neto-SAP** [comment]
TBD/Aligned with Fiedler, Thomas <thomas.fiedler@sap.com> and Dierkes, Gerhard <gerhard.dierkes@sap.com

**Comment by eugen-guenther-sap** [comment]
suggestions about the keywords in ABAP are welcome :)

**Comment by lucasborin** [comment]
Please, correct me if I am wrong: It is the Nesting Depth rule, however counting the multiple `AND`s, `OR`s, `ELSEIF`s, and `CATCH`es as well.

**Comment by lucasborin** [comment]
Isn't it a brand new name for the number of branches? 

Based on the [Cognitive Complexity](https://docs.codeclimate.com/docs/cognitive-complexity): 

> When a method's logic flows from top to bottom, it is very easy to understand.

Then, fewer branches mean less cognitive complexity. 

> The for `loop` changes the function so it no longer flows directly from top to bottom, but now loops in circles a few times in the middle, which contributes to the Cognitive Complexity for the reader. It's a small thing, but it adds up.

> Other examples of breaks in flow:
> - loops
> - conditionals
> - catching/rescuing exceptions
> - switch or case statements
> - sequences of logical operators (e.g. a || b && c || d)
> - recursion
> - jumps to labels

More branches...

**Comment by estevao-schultz-neto-SAP** [comment]
I think the nesting depth should not count ANDs, ORs, CATCHes or ELSEIFs. Let me exemplify:

IF a AND b.
  "nesting depth = 1
ELSEIF.
  "nesting depth still = 1
ENDIF.

Now here:

IF a AND b.
  "nesting depth = 1
  IF c OR d.
     "nesting depth = 2
     DO x TIMES.
          "nesting depth = 3
     ENDDO.   
  ENDIF. 
ELSEIF.
  ...
ENDIF.

**Comment by estevao-schultz-neto-SAP** [comment]
more or less, a fancy name for branch complexity (cognitive due to what our brain is able to follow).

**Comment by lucasborin** [comment]
So, can we reuse the `AUNIT` framework to get the branch coverage per method? I guess so...

**Comment by estevao-schultz-neto-SAP** [comment]
Not sure. How you would know the deepth? 

void myMethod () {
 try {
 if (condition1) { // +1
 for (int i = 0; i < 10; i++) { // +2 (nesting=1)
 while (condition2) { … } // +3 (nesting=2)
 }
 }
 } catch (ExcepType1 | ExcepType2 e) { // +1
 if (condition2) { … } // +2 (nesting=1)
 }
} // Cognitive Complexity 9
--------------------------------------------------
void myMethod2 () {
 Runnable r = () -> { // +0 (but nesting level is now 1)
 if (condition1) { … } // +2 (nesting=1)
 };
} // Cognitive Complexity 2

-----------------------------------------------------------------------
#if DEBUG // +1 for if
void myMethod2 () { // +0 (nesting level is still 0)
 Runnable r = () -> { // +0 (but nesting level is now 1)
 if (condition1) { … } // +3 (nesting=2)
 };
} // Cognitive Complexity 4
#endif

**Comment by lucasborin** [comment]
The depth is part of the branch logic itself. You don't need to calculate it.

The `AUNIT` framework provides you the number of branches once the object has a test class for it.

For instance:

![image](https://user-images.githubusercontent.com/5233413/114890139-204c3600-9de1-11eb-993e-9082e15215a3.png)

The `ADJUST_MOVEMENT_DIRECTION` has a Cognitive Complexity of 7.

**Comment by estevao-schultz-neto-SAP** [comment]
coooool !!! Then one more CHECK is ready :-)

**Comment by lucasborin** [comment]
> coooool !!! Then one more CHECK is ready :-)

I have not gone that deep, but the AUNIT will provide it if the object has a unit test.

**Comment by eugen-guenther-sap** [comment]
so basically i will close this issue, cause there is no need to have a fancy name for branch coverage.
