### ISSUE TITLE
New check: non-exhaustive case statement

### ISSUE THREAD

**Issue by FreHu** [SAP/code-pal-for-abap#28]
Example: I have a domain with 3 fixed values. Then every case statement based on that domain not covering all three is suspicious. 

Even more importantly, if you extend the domain with a fourth value later, all existing switches should be reviewed to make sure the new value is handled correctly.

**Comment by flaiker** [comment]
> Then every case statement based on that domain not covering all three is suspicious. 

Unless there's a `WHEN OTHERS`, right?

**Comment by FreHu** [comment]
I'd check that the number of `when`s is equal to the number of domain values. This would allow a when others branch, but I think for fixed it is cleaner to avoid using `when others` in favor of enumerating all cases.

Example:

domain values are x, y, z. 

Compare

```abap
case domain_typed_variable.
  when `x`.
   " something
  when `y`.
   " something
  when `z`.
   " something
endcase.
```

```abap
case domain_typed_variable.
  when `x`.
   " something
  when `y`.
   " something
  when others.
   " something
endcase.
```

*   I need to look up what domain value the \`others\` case is referring to - this hurts readability
*   when the domain is extended, `when others` will cover one more case than before. It's not guaranteed that the when others branch is future-proof enough to behave correctly for the new value.

Often I add an assert or an exception to the when others case to future-proof the code.

```abap
case domain_typed_variable.
  when `x`.
   " something
  when `y`.
   " something
  when `z`.
   " something
  when others.
   ASSERT 1 = 0. " if you're seeing this, the domain was extended
endcase.
```

```abap
case domain_typed_variable.
  when `x`.
   " something
  when `y`.
   " something
  when `z`.
   " something
  when others.
   raise exception new cx_basically_an_assert( ).
endcase.
```

**Comment by flaiker** [comment]
I agree I usually also have some kind of cx_unsupported_operation exception in the others block.

Enumerating all values though? There are domains with dozens of values. There are also domain appends that could even be used down the transport route, so you kind of always need to assume someone just adds a fixed value and your code needs to deal with it (instead of just shortdumping with an assertion :P)

And then there are also domains which use the range feature instead of just fixed values.

**Comment by FreHu** [comment]
Yeah, it's hard to cover everything. I always propose things based on what I work with, and I don't encounter domain appends or >10 fixed values. Still, I think if you ran this check across all SAP code you'd find _a lot_ of bugs.

**Comment by D072189** [comment]
While a very good idea for a check (even if we'd accept a WITH OTHERS clause as covering non-enumerated values), this doesn't seem to be currently covered by any section in the [style guide](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md), hence I don't think this is appropriate as part of CodePAL - if you think this should be part of the Clean ABAP guidelines, please get it into the guide first.

**Comment by pokrakam** [comment]
I think this is for quite a specific subset of CASE statements, which IMHO should possibly be implemented as Enumeration classes with unit tests for domain coverage. 

This is nicely described in the style guide [over here](https://github.com/SAP/styleguides/blob/main/clean-abap/sub-sections/Enumerations.md#prefer-classes-to-interfaces), and I like the idea of a domain-based-CASE check, might just implement one myself. A valid check (also within the style guide) could be that a domain-typed variable should not be checked against literals but against a constant.

For what it's worth, the Clean Code book prefers polymorphic classes over `CASE` scenarios (chapter 3, section _Switch Statements_). So the above `CASE` example and its `something`'s could be replaced with:
```
something_factory=>get_instance_for( domain_typed_variable )->do_something( ).
```
and the `CASE`'s content is abstracted one level lower down. But that's one for the style guide 🙂
