### ISSUE TITLE
Prefer REF TO to FIELD-SYMBOL

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#280]
https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#prefer-ref-to-to-field-symbol

**Comment by D072189** [comment]
Since the section is being challenged due to REF TO being less performant than FIELD-SYMBOL, we probably shouldn't create a check that tells people to make their code slower.

**Comment by ConjuringCoffee** [comment]
The section was removed in: https://github.com/SAP/styleguides/pull/307
I suggest closing this issue 😊
