### ISSUE TITLE
Unit Test Without/With Invalid Assert

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#288]
- Checks methods with no assert at all.
- Checks methods with more than one assert (if they make sense) (?)
- Checks methods with fake asserts (same values for exp = act).

**Comment by suhaskoul** [comment]
Hi,
We wish to see a check coming during code-pal plugin in SCI where no assert statement is written in a method. 
Does this pull request take care of that or is there a new check for this .

BR
Suhas
