### ISSUE TITLE
Check outside of main report package

### ISSUE THREAD

**Issue by gaelrech** [SAP/code-pal-for-abap#295]
Reports that have includes that belong to different packages (e.g. payroll drivers) will run Code Pal for these objects as well - even though they may not belong to your "scope".

Example: 

- Report A belongs to package PACK1
- Report A includes the source code objects INC1, which belongs to the package PACK2 (this could be a basis include, etc.) 

In case changes are applied to the object INC1 after the profile effective date, it will show as an error in report A - even though they are in different packages and application components.

**Comment by lucasborin** [comment]
Probably, we will have to check if they...
1. Belong to the same package;
2. Or, belong to the same application component.

**Comment by gaelrech** [comment]
Seems that the right place would be to add a check inside `Y_CHECK_BASE->DETECT_CHECK_CONFIGURATION`.

1. Read TADIR for both the main report and the current processed object to compare both packages
2. Read TADIR for both the main report and the current processed object, use the package to read TDEVC and then compare the application components
