### ISSUE TITLE
CHECK POSITION Sill Not working

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#301]
My understanding is that if a CHECK statement is the very first statement in a method then a warning should not be issued.

![image](https://user-images.githubusercontent.com/7078215/104247570-2a962580-54bc-11eb-8304-76c7df423a44.png)

![image](https://user-images.githubusercontent.com/7078215/104247609-3da8f580-54bc-11eb-8560-1997cc8562d9.png)

If I remove the comment then the warning goes away. However I do not think it is unreasonable to have comments at the start of some methods, to explain the WHY of the method i.e. the business reason behind it's existence or why it does things in a non-standard way.

**Comment by lucasborin** [comment]
I've fixed it in the next release (1.11.0), which is under test now. 
Feel free to import the respective branch to test it. :)

**Comment by lucasborin** [comment]
version released. Could you please test it again?
