### ISSUE TITLE
Empty catch should be removed! But not in test class

### ISSUE THREAD

**Issue by licheng5625** [SAP/code-pal-for-abap#332]
In our test classes, we are using test double framework . 
Here is the syntax how to config the call.
cl_abap_testdouble=>configure_call( double = item )->ignore_all_parameters( )->returning( ref_item ).
    TRY.
        item->get_referenced_item( logger = logger ).
      CATCH cx_apoc_object.
    ENDTRY. " exception for apoc object class

We need the dummy try and catch to avoid ATC check, which trigger the empty catch error all the time.

Please review if this check makes sence in  test class.

**Comment by lucasborin** [comment]
Hi @licheng5625,

If it's a positive test, the unit test should raise a failure if the respective method raises the exception:

```abap
TRY.
    item->get_referenced_item( logger = logger ). 
  CATCH cx_apoc_object.
    cl_aunit_assert=>fail( msg = '...' ). 
ENDTRY. " exception for apoc object class
```

If it is a negative test, the unit test should raise a failure if the method does not raise the exception, and what should happen with the `item` class? can we test if it's still bound?

```abap
TRY.
    item->get_referenced_item( logger = logger ). 
    cl_aunit_assert=>fail( msg = '...' ). 
  CATCH cx_apoc_object.
    cl_aunit_assert=>assert_bound( item ). 
ENDTRY. " exception for apoc object class
```

Regards,
Lucas

**Comment by licheng5625** [comment]
Hi，
this is the sytax of ABAP test double framwork  cl_abap_testdouble=>configure_call( double = item )->ignore_all_parameters( )->returning( ref_item ).
  **item->get_referenced_item( logger = logger ).**  is really called. 
So that it will be never raise any exception here.

I could config it to raise exception 
  cl_abap_testdouble=>configure_call( double = item )->ignore_all_parameters( )->raise_exception( xxx ).
  **item->get_referenced_item( logger = logger ).**  is really called. 
It will raise exception at Production Code, not here. 
Try and catch here is just a work round to avoid ATCs.

**Comment by lucasborin** [comment]
Check with ATC colleagues if they can also exempt it.

**Comment by lucasborin** [comment]
It's a fake call required for the test double framework. Therefore, the code pal should somehow exempt it.

**Comment by lucasborin** [comment]
Mail sent to ATC colleagues.
