### ISSUE TITLE
Y_CHECK_DB_ACCESS_IN_UT on INSERT INTO internal table.

### ISSUE THREAD

**Issue by LeonidPesin** [SAP/code-pal-for-abap#348]
Similar problem to what was fixed in "[Y_CHECK_DB_ACCESS_IN_UT on DELETE from internal table](https://github.com/SAP/code-pal-for-abap/issues/290)".
Now the same error happens on
    INSERT message INTO TABLE mt_messages.
in CL_HRPAO_DPR_CHLDC_LEAVING_RU.
The class was not changed for months, but the error arises just 3 days ago in EHR.

**Comment by lucasborin** [comment]
Fix implemented in EHR. Could you please test it?

**Comment by lucasborin** [comment]
Fixed in 1.31.1, Implemented in EHR.

**Comment by LeonidPesin** [comment]
Thank you, Borin! The error is gone.
