### ISSUE TITLE
Catch CX_ROOT

### ISSUE THREAD

**Issue by RolfMantel** [SAP/code-pal-for-abap#356]
In docs/checks/cx-root-usage.md you explain what this check is doing but there is not a word about the "why".

You like to the style guide "use class-based exceptions", and the style guide does not mention CX_ROOT at all.

It is meaningful to request avoidance of CX_ROOT when there is a more meaningful alternative but sometimes there isn't.

In conclusion, this check should be a warning rather than an error.

**Comment by lucasborin** [comment]
Long thread about exceptions, including comments about `cx_root`: https://github.com/SAP/styleguides/issues/138

**Comment by estevao-schultz-neto-SAP** [comment]
I think no one understands "your business" better than yourself. Delivered Exceptions are usually generic ones. Every component/product/area should pursuit their own (business) exception classes. Especially when missing. Just a short example: 2 divided by 0 could throw cx_root (or a well defined exception: Error Divide By Zero).

**Comment by lucasborin** [comment]
> In docs/checks/cx-root-usage.md you explain what this check is doing but there is not a word about the "why".

For instance, if you find your team is not handling the exceptions properly, you can use this check to recommend them to create well-defined exceptions for each specific kind of issue. Then, once you catch the right exception, you can guide the end-user on how to solve the issue. 

Personally, I see most of the `CX_ROOT` catches translating a short dump to the end-user as `Ok, we found an error, please raise an incident`. So, in this way, what is the difference between the error message and the short dump? (besides exiting the program). If it is, for instance, a customizing issue, it would be better to avoid the incident and guide the user to fix the customizing directly. 

> It is meaningful to request avoidance of CX_ROOT when there is a more meaningful alternative but sometimes there isn't.

There are some exceptional cases where `CX_ROOT` is required, and you can bypass it using the pseudo comment. 
You can see issue #337 for further information.

> In conclusion, this check should be a warning rather than an error.

It looks like an SAP internal process. Let's share this feedback with them directly as it is not a tool decision. 

On the code pal side, you can turn off the check if it is not relevant to your scenario. 
So, no changes required. 

If you do not mind, I will close this issue.
