### ISSUE TITLE
Diffs for TABL

### ISSUE THREAD

**Issue by larshp** [SAP/code-pal-for-abap#359]
TABL format was changed ~1 month ago in the latest abapGit version, https://github.com/abapGit/abapGit/blob/main/changelog.txt#L27

![image](https://user-images.githubusercontent.com/5888506/113896754-85dd6880-97ca-11eb-925b-b9546855a6fd.png)

![image](https://user-images.githubusercontent.com/5888506/113896770-883fc280-97ca-11eb-8db3-26ba4b206647.png)

**Comment by lucasborin** [comment]
@larshp: Should I remove them manually, or the abapGit has a feature to remove them for us?

**Comment by larshp** [comment]
update your system to the latest abapGit, then it will automatically suggest the changes to be commited
