### ISSUE TITLE
Changed values are not saved

### ISSUE THREAD

**Issue by jrodriguez-rc** [SAP/code-pal-for-abap#36]
I'm trying to change the values for some checks (Cyclomatic Complexity and Number of Executable Statements) and they remain with the default value instead of changed.

**Comment by estevao-schultz-neto-SAP** [comment]
Thanks for reporting this issue. We will check and come back to you asap.

**Comment by eugen-guenther-sap** [comment]
Hello,
thank you for reporting this issue.
it should be fixed now.

**Comment by jrodriguez-rc** [comment]
In SCI transaction now loads the saved values, but executing ATC is getting the default values instead of saved:
![image](https://user-images.githubusercontent.com/56556686/86907381-38d24600-c115-11ea-8bed-bc7a18a41aaf.png)

**Comment by eugen-guenther-sap** [comment]
solved :)

**Comment by jrodriguez-rc** [comment]
Now is working correctly, thank you!
