### ISSUE TITLE
Y_CHECK_CALL_METHOD_USAGE: Readability of code will be decreased

### ISSUE THREAD

**Issue by eiseleh** [SAP/code-pal-for-abap#373]
In my opinion the coding is readable if it is like a natural language. "Call method" is therefore better readable than brackets at the end. If "call method" is not used the reader always have to look at the end of the object which will be used, to see whether a method is called and not a property.
It is clear that method chaining needs to omit "Call method" but I don't see any issue with usage of call method for simple methods calls and calling the short form if necessary.

**Comment by lucasborin** [comment]
Hi @eiseleh, thanks for sharing it.

Clean ABAP > Content > Methods > Calls > [Prefer functional to procedural calls](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#prefer-functional-to-procedural-calls):

> Prefer functional to procedural calls instead of the needlessly longer ... `CALL METHOD`

Clean ABAP > Content > Language > [Prefer functional to procedural calls](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#prefer-functional-to-procedural-language-constructs):

> They are usually shorter and come more natural to modern programmers.

As code pal follows the Clean ABAP recommendations, I recommend you start a new thread in the [Clean ABAP](https://github.com/SAP/styleguides/issues/) GitHub sharing your perspective. Let's follow up together there. 

Best Regards,
Lucas
