### ISSUE TITLE
The error message is wrong in the new CHECK ASSERT (Unit-Test Assert Validator)

### ISSUE THREAD

**Issue by estevao-schultz-neto-SAP** [SAP/code-pal-for-abap#387]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md) style guide. If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
Unit-Test Assert Validator

**Actual Behavior**
Error message by findings is wrong : ==> Maintain Attributes for the Code Inspector Check!

**Expected Behavior**
The error message of the check should appear

**Comment by lucasborin** [comment]
It means the code inspector variant is broken. Which system?

**Comment by estevao-schultz-neto-SAP** [comment]
ER9. I have opened and saved the variant again (last changed NETOE). This seems not to be the problem.

**Comment by lucasborin** [comment]
I updated the code pal in ER9 to 1.14.1, and it is working now.

![image](https://user-images.githubusercontent.com/5233413/117133909-3ebba680-ad7b-11eb-92ee-9ba89a6e3edf.png)

Could you please try again?
