### ISSUE TITLE
New check for AUnit code with RAISING CX_STATIC_CHECK

### ISSUE THREAD

**Issue by eX0du5-galaxytool** [SAP/code-pal-for-abap#392]
**Check Name**
A new check for AUnit code for RAISING CX_STATIC_CHECK

**Expected Behavior**
One new Check could be to raise any missing declaration of “RAISING CX_STATIC_CHECK” for test methods. People oftentimes then add TRY CATCH blocks to get rid of the warnings but either do not handle the catch (code smell) or handle it in a way that it fetches the get_message() text and fails with it. But this is exactly the code that would be triggered with the RAISING CX_STATIC_CHECK and would thus make the code much cleaner.

**Comment by lucasborin** [comment]
Unfortunately, I have not found any direction on this matter in the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md) style guide. Have you found something there?
If you haven't, how about opening an issue asking their perspective before creating the new check?

**Comment by eX0du5-galaxytool** [comment]
I asked this as part of the preview for those checks SAP internally and got asked to create the issue here - independently of the Clean Style Guide book.

**Comment by D072189** [comment]
There currently seems to be no section in the [style guide](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md) that actually recommends this. 

If you think this should be part of the Clean ABAP style, please open an issue there first. We understand that there are valid reasons to want checks for things that are not part of the Clean ABAP style guide, but CodePAL is not intended to implement all kinds of checks that would be nice to have - it is specifically focused on the Clean ABAP style.
