### ISSUE TITLE
Equals Sign Chaining does not check the variable type

### ISSUE THREAD

**Issue by nomssi** [SAP/code-pal-for-abap#398]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md) style guide. If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
Equals Sign Chaining

**Actual Behavior**
            lo_cell = lo_cell->cdr = lcl_lisp_new=>cons( io_car = lo_peek ).
is reported (Values should not be allocated more than once within one statement).

**Expected Behavior**
No finding should be reported, The check should only search for chained assignments of **boolean** variables.

**Comment by lucasborin** [comment]
Yeah, based [its documentation](https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/equals-sign-chaining.md), the Check should handle boolean attributes/variables only:

> **What is the Intent of the Check?**
> This check searches for chained **boolean** assignments in the code which might generate some confusion with an equal condition.

By the way, I have not found any guidance from the Clean ABAP style guide on this matter.  
Let me ask for their support here.

**Comment by lucasborin** [comment]
Actually, the same 'confusion' happens in the object assignment when it is chained.

```abap
DATA a TYPE string VALUE 'A STRING'.
DATA b TYPE string VALUE 'B STRING'.
DATA c TYPE abap_bool.

c = a = b.
```

Ps:  `c` will receive the first character from `b`, as the `abap_bool` is `char1`, and not `abap_false`.

**Comment by lucasborin** [comment]
It looks like that most of the people follow the comment shared by Lars:
> In my opinion: avoid using chained assignment in all cases, its rarely used in actual code, and easy to work around

Therefore, I prefer changing the documentation instead of changing the logic to validate boolean types only.

**Comment by estevao-schultz-neto-SAP** [comment]
I agree with the opinion of Lars too (I would avoid chained assignments in all cases -- for the sake of fast code reading). But following the style-guides, it should be only applied to boolean types. Especially when we are stating this too:

💡 Code pal for ABAP follows the Clean ABAP style guide. If the issue relates to coding style, please submit it here.

But we could also contact the Style-Guide colleagues and enhance on both sides to apply the check to all types.
