### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#4]
I click on all the check boxes of the new "Y" checks and then press SAVE. I get an error message as follows:-

![image](https://user-images.githubusercontent.com/7078215/81137978-c1acf400-8fa3-11ea-8c78-09f92a392e16.png)

It tells you have to fix the problem but again, I just thought I would mention it.

**Comment by maxim-engel-sap** [comment]
That is true. I added a comment in the README to prevent this error.
