### ISSUE TITLE
Not runnable under 7.40

### ISSUE THREAD

**Issue by BlackmanCC** [SAP/code-pal-for-abap#40]
CodePal does not run under 7.40 because class y_check_base has a syntax error.

In constructor the instance attribute of referenced class CL_CI_TEST_ROOT is set

me->remote_rfc_enabled = abap_true.

This attribute does not exist under 7.40.

**Comment by eugen-guenther-sap** [comment]
Thank you for reporting.
It should be solved now.

**Comment by BlackmanCC** [comment]
Thank you very much for the fast solution.
