### ISSUE TITLE
Different check results

### ISSUE THREAD

**Issue by LeonidPesin** [SAP/code-pal-for-abap#404]
**Check Name**
> Y_CHECK_CYCLOMATIC_COMPLEXITY

**Actual Behavior**
> Checking class CL_HRPAYRU_RMS_CITAX_NODE_TREE with GS profile in system HRI/000 brings the error:
Cyclomatic Complexity on method MAP_TAX_LINE.
Checking the same object by the same profile in system EHR/001 shows no errors at all.
What's the difference in the checks between two systems?

**Expected Behavior**
> Check results of the same object should be identical in all the systems running the checks.

**Comment by lucasborin** [comment]
code pal is not up to date in the HRI system

Current Version = 1.14.2
EHR = 1.14.2
HRI = 1.11.0

**Comment by LeonidPesin** [comment]
Is it expected to be upgraded in HRI? 
Or should we stop checking there?

**Comment by lucasborin** [comment]
HRI updated. Could you please test again?
