### ISSUE TITLE
Do not report CHECK in LOOP, if CHECK is the first statement 

### ISSUE THREAD

**Issue by suynwa** [SAP/code-pal-for-abap#437]
**Check Name**
> CHECK in LOOP

**Actual Behavior**
 The check reports the usage of CHECK inside LOOP...ENDLOOP always irrespective of the fact that the CHECK is the first statement in LOOP...ENDLOOP.

**Expected Behavior**
 The check should not report the usage of CHECK if it is the first statement inside the LOOP...ENDLOOP 
IMHO, the below code snippet is more legible and cleaner 

``` abap
loop at COMPANIES assigning field-symbol(<COMPANY>).
  check _IS_COMPANY_IN_EU( <COMPANY> ).
  ...
endloop.
```
than

``` abap
loop at COMPANIES assigning field-symbol(<COMPANY>).
  if not _IS_COMPANY_IN_EU( <COMPANY> ).
    continue.
  endif.
  ...
endloop.
```
Even the standard ABAP [documentation](https://help.sap.com/doc/abapdocu_755_index_htm/7.55/en-US/abapcheck_loop.htm) recommends to use CHECK inside LOOP.

**Comment by lucasborin** [comment]
Hi Suynwa,

Code pal follows the Clean ABAP style guide, and they mentioned:

> Do not use CHECK outside of the initialization section of a method. The statement behaves differently in different positions and may lead to unclear, unexpected effects.

> For example, CHECK in a LOOP ends the current iteration and proceeds with the next one; people might accidentally expect it to end the method or exit the loop. Prefer using an IF statement in combination with CONTINUE instead, since CONTINUE only can be used in loops.

Source: [Avoid CHECK in other positions](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#avoid-check-in-other-positions)

Would you mind reporting it in the [Clean ABAP](https://github.com/SAP/styleguides/issues/new) directly? The experts will evaluate your suggestion and adjust the style guide, if necessary. Afterward, we can adjust the code pal too.

Lucas

**Comment by suynwa** [comment]
Hi Lucas, i have raised the question in the Clean ABAP Github page. Thanks for your feedback.

BR, Suhas

**Comment by lucasborin** [comment]
Good, thanks!

By the way, we decided to split the CHECK validation in two based on feedback received in the past (#223). 

Now:
* [CHECK Statement Position Check](https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/check-statement-position.md) does not report CHECK in LOOPs
* [CHECK in LOOP](https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/check-in-loop.md) reports CHECK in LOOPs only.

**Comment by suynwa** [comment]
Splitting the CHECK validation makes absolute sense. IMO, the Clean ABAP guideline to avoid CHECK inside LOOPs is to ensure that the developers who refuse to RTFM do not accidentally misuse

**Comment by D072189** [comment]
Since this exception is not (yet?) part of the Clean Code style guide, I'm closing this issue. Please open a new issue if "CHECK as first statement of LOOP" becomes part of the style guide one day.
