### ISSUE TITLE
Avoid Unnecessary Multiple Calls

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#445]
If in a unit another unit is called more than once (respecting its parameters), ask the user to use a local variable instead to avoid unnecessary calls (performance).

For instance, from:
```abap
"anti-pattern
METHOD example.
  IF system=>get_type() = 'PROD'.
    ...
  ELSEIF system=>get_type() = 'QA'.
    ...  
  ENDIF.
ENDMETHOD.
```

To:
```abap
METHOD example.
  DATA(system_type) = system=>get_type().
  IF system_type= 'PROD'.
    ...
  ELSEIF system_type = 'QA'.
    ...  
  ENDIF.
ENDMETHOD.
```

**Comment by pokrakam** [comment]
Interesting idea, but how will you distinguish between avoidable and valid uses?
Things like `log->write( )` `counter->increment( )`
Or genuine repetitions:
```ABAP
METHOD build_page_table.
  html->add_row( ).
  html->add( get_some_info( ) ).
  html->add_row( ). 
  html->add( get_other_info( ) ).
ENDMETHOD.
```

**Comment by lucasborin** [comment]
Tricky scenario. We could check for methods that are being assigned to variables or used in conditional statements.

However, the following statement will raise a false positive:
```abap
METHOD build_page_table.
  html->add_row( ).
  html->add( get_some_info( ) ).

  IF html->reached_max_lines( ) = abap_true.
    re
  ENDIF.

  html->add_row( ). 
  html->add( get_other_info( ) ).
ENDMETHOD.
```

**Comment by lucasborin** [comment]
In the beginning, my idea was to get all the methods in which the result is being assigned to a variable or used in a conditional statement. It would skip the above-mentioned example.

But, not the below example:
```abap
calc->add(10);
calc->add(15);
sum = calc->get_sum();

calc->add(20);
calc->add(25);
sum = calc->get_sum(); "<===
````

**Comment by lucasborin** [comment]
How about if the Check reports an error only when there is no interaction with the class between the two repeated calls?
I know, it will not report all the issues, but at least some to raise the concern.

For instance: 
```abap
calc->add(10);
calc->add(15);
sum = calc->get_sum();

do_some_stuf( );
sum = calc->get_sum(); "<===
```

And not:
```abap
calc->add(10);
calc->add(15);
sum = calc->get_sum();
calc->add(10);
calc->add(15);
sum = calc->get_sum(); 
```

**Comment by D072189** [comment]
This would only make sense if ABAP was a pure functional language where repeated calls to the same method with the same inputs a) always yield the same results and b) have no side-effects. Neither of these is true for ABAP, so it's essentially impossible to avoid false positives for this check. 

In imperative languages like ABAP, there are many cases where the return value of a method call changes over repeated calls. A simple example is a traditional iterator pattern: Calling `NEXT` on an iterator will return the next element in the iterator's queue, and - depending on the caller's knowledge of the structure of the iterator - it is perfectly valid to discard the result of doing that and call `NEXT` multiple times in a row.

Therefore I don't think this check has any chance of attaining an acceptably low false positive rate.
