### ISSUE TITLE
IS BOUND should be used to check that a reference is valid instead of IS NOT INITIAL

### ISSUE THREAD

**Issue by suynwa** [SAP/code-pal-for-abap#472]
**Check Name**
Not yet available

**Actual Behavior**
Not applicable

**Expected Behavior**
IS BOUND should be used to check that a (data/object) reference variable contains a valid reference. For reference variables containing invalid references IS NOT INITIAL = 'True' but IS BOUND = 'False'.

For further details please check Horst Keller's blog https://blogs.sap.com/2016/10/14/invalid-references

**Comment by D072189** [comment]
There currently seems to be no section in the [style guide](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md) that actually recommends this. 

If you think this should be part of the Clean ABAP style, please open an issue there first.
