### ISSUE TITLE
use native *_wa variables

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#474]
Strangely, Code Pal was built not using the "*_wa" variables (`structure_wa`, `statement_wa`, and `token_wa`). Most of the native features available in the Code Inspector use these variables. Therefore, let's change it.

**Comment by pokrakam** [comment]
Why? 
I find a simple name perfectly readable:
```ABAP
  LOOP AT statements INTO data(statement).
    IF statement-token[ 1 ].
    ...
```
vs. 
```ABAP
  LOOP AT statements INTO data(statement_wa).
    IF statement_wa-token[ 1 ].
    ...
```
Why do we need to pollute it with `_wa`, what do we gain'?
In my opinion this is just another old naming habit that we are trying to get away from.
