### ISSUE TITLE
Complex Local Structures

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#487]
A new Check could search for complex local declared structures and suggest splitting them up into multiple local types.

For instance:

```abap
"anti-pattern
DATA: BEGIN OF html,
        BEGIN OF header,
          title TYPE i,
        END OF header,
        BEGIN OF body,
          message TYPE i,
        END OF body,
        BEGIN OF footer,
          message TYPE i,
        END OF footer,
      END OF html.
```

To:

 ```abap
TYPES: BEGIN OF header,
          title TYPE i,
       END OF header.
            
TYPES: BEGIN OF body,
          message TYPE i,
       END OF body.
            
TYPES: BEGIN OF footer,
          message TYPE i,
       END OF footer.
      
DATA: BEGIN OF html,
         header TYPE header,
         body TYPE body,
         footer TYPE footer,
       END OF html.
```

**Comment by D072189** [comment]
There currently seems to be no section in the [style guide](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md) that actually recommends this. 

If you think this should be part of the Clean ABAP style, please open an issue there first. 

In this case I wholly agree that this is bad style, and the correct recommendation should probably be to _never_ use `DATA BEGIN OF` but instead always to declare a proper type. The type of variables declared with `DATA BEGIN OF` is impossible to name explicity and makes it thereby e.g. impossible to perform refactorings where a variable of the same type should become a method parameter. That is, even your final solution is still questionable, and it should be

```abap
TYPES: BEGIN OF header,
         title TYPE i,
      END OF header.
           
TYPES: BEGIN OF body,
         message TYPE i,
      END OF body.
           
TYPES: BEGIN OF footer,
         message TYPE i,
      END OF footer.

TYPES: BEGIN OF html,
        header TYPE header,
        body TYPE body,
        footer TYPE footer,
      END OF html.
     
DATA html TYPE html.
```

instead.
