### ISSUE TITLE
Check for CHECK Statements

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#5]
The style guide says to use CHECK statements at the start of methods, but nowhere else. 

The below gives two warnings:-

![image](https://user-images.githubusercontent.com/7078215/81139282-911b8900-8fa8-11ea-91b0-f17f34ad05e6.png)

Often you need comments above the CHECK to explain to the reader what is going on. Often you need several CHECK statements.

Even if you disagree in my example CHECK is in fact the first STATEMENT but the check says it is not and that is clearly wrong.

Therefore if the first (say) three statements (not comments) in a method are OK, you should let it go.

**Comment by hardyp** [comment]
And what about DATA declarations? Sometimes you still need them as well even according to the Clean ABAP guidelines e.g. to avoid a declaration inside an IF. They (DATA) would trigger the warning though they are not statements in the sense the check is looking for either.

**Comment by eugen-guenther-sap** [comment]
Thank you, the update is online now.
