### ISSUE TITLE
False Positive: New instead of Create Object should not be applied if "for testing" is used

### ISSUE THREAD

**Issue by PeregrinTooc** [SAP/code-pal-for-abap#511]
**Check Name**
prefer-new-to-create-object

**Actual Behavior**
For RAP, implementation classes can only be instantiated with the addition "for testing":

```ABAP
data cut type ref to rap_implementation.
create object cut for testing.
```

Code Pal enforces the usage of a pragma since `new` is preferred.

**Expected Behavior**

If the addition `for testing` is used, do not apply the check

**Comment by lucasborin** [comment]
Hello @PeregrinTooc, thanks for reaching us. 

We fixed it recently, and the correction is available in the `master` branch.
Ref: RAP needs CREATE OBJECT ... FOR TESTING (#444 #448).

Is your code pal updated?

Kind Regards,
Lucas

**Comment by lucasborin** [comment]
Feel free to reopen the thread if the issue persists.
