### ISSUE TITLE
Error in  Empty Procedure check

### ISSUE THREAD

**Issue by jrodriguez-rc** [SAP/code-pal-for-abap#52]
In a FORM looping screen the check is detecting that is empty:
![image](https://user-images.githubusercontent.com/56556686/88267853-c1361680-ccd1-11ea-9e06-0bb5e32ec4a5.png)

**Comment by eugen-guenther-sap** [comment]
Thank you, it should be solved now.

**Comment by jrodriguez-rc** [comment]
Thank you, it is working now.
