### ISSUE TITLE
Prefer Alpha IN/OUT to Handle Leading Zeros

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#520]
**For Removing Leading Zeros**

instead of:
```abap
DATA var_int TYPE char10 VALUE '0000098765'.
DATA var_ext TYPE char10.

CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT' 
  EXPORTING
    input  = var_int
  IMPORTING
    output = var_ext.  
```
use:
```abap
DATA var_int TYPE char10 VALUE '0000098765'.
DATA(var_ext) = |{ var_int ALPHA = OUT }|.
```

**For Adding Leading Zeros:**

instead of:
```abap
DATA var_ext TYPE char10 VALUE '12345'.
DATA var_int TYPE char10.

CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT' 
  EXPORTING
    input  = var_ext
  IMPORTING
    output = var_int.
```
use:
```abap
DATA var_ext TYPE char10 VALUE '12345'.
DATA(var_int) = |{ var_ext ALPHA = IN }|.
```

Reference: [ABAP 7.4 and beyond [11] : Concatenation, ALPHA and ITAB Lines](https://discoveringabap.com/2021/11/04/abap-7-4-and-beyond-11-concatenation-alpha-and-itab-lines/)

**Comment by lucasborin** [comment]
One more alternative to add the leading zeros:

```abap
DATA input(16).
DATA output(6) TYPE c VALUE '123456'.

unpack output to input.
```

Reference: [Add Leading Zeros in ABAP](https://sap4tech.net/add-leading-zero-abap/)

**Comment by lucasborin** [comment]
One more alternative to removing the leading zeros:

```abap
SHIFT variable LEFT DELETING LEADING space.
```´

**Comment by D072189** [comment]
There currently seems to be no section in the [style guide](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md) that actually recommends this. 

If you think this should be part of the Clean ABAP style, please open an issue there first.
