### ISSUE TITLE
Remove static dependency to developer version of abapGit

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/code-pal-for-abap#524]
Class Y_CODE_PAL_SERVICE has a dependency to the developer version of abapGit. In method EXECUTE_GET_VERSIONS it uses ZIF_ABAPGIT_VERSION=>GC_ABAP_VERSION. This causes a syntax error if only abapGit standalone version (or no abapGit) is installed.

Is it possible to remove this static dependency? Maybe use the parameter dynamically and handle it with an exception if abapGit is not installed?

**Comment by lucasborin** [comment]
We can drop it. I created it in the past to <try to> automate the code pal upgrade in some internal systems, but it is no longer in use.
