### ISSUE TITLE
Unit test GLOBAL_TEST_CLASS in Y_CHECK_BASE fails

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/code-pal-for-abap#525]
The unit test method `GLOBAL_TEST_CLASS` of class `Y_CHECK_BASE` fails. It expects a true boolean value for `IS_TEST_CODE`, but it is false. 
I can confirm that `Y_UNIT_TEST_BASE` is available in the system, containing test code on the global class level.

I'm running the tests of commit c782c26 on an S/4 system with component SAP_BASIS release 755 SP-Level 0002. Can anyone confirm if the test runs successfully on older releases?

**Comment by ConjuringCoffee** [comment]
Please note that this isn't the only unit test that fails in my system: #526 
The issues might be connected.

**Comment by lucasborin** [comment]
Tested on SAP_BASIS 757/0000:
![image](https://user-images.githubusercontent.com/5233413/141112570-ae2e0a9a-e5e0-4faa-8a22-c639a8685419.png)

All fine here. Is the latest version of the class `y_code_pal_ref_scan_double` active on your system?

**Comment by ConjuringCoffee** [comment]
Interesting. Yes, the latest version is active and identical to the code on GitHub.

**Comment by ConjuringCoffee** [comment]
It looks like the task of implementing that note fell through on our side. I'll see to it being implemented and will report back.

**Comment by ConjuringCoffee** [comment]
Implementing Note 2527903 fixed the issue, thanks.
