### ISSUE TITLE
Unit test RFC_ENABLED in Y_CHECK_FUNCTION fails

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/code-pal-for-abap#526]
The unit test method `RFC_ENABLED`  of class `Y_CHECK_FUNCTION` fails. It expects an initial value for `cut->get_statistics( )->count-notes`, but it contains the number 3.

I'm running the tests of commit c782c26 on an S/4 system with component SAP_BASIS release 755 SP-Level 0002. Can anyone confirm if the test runs successfully on older releases?

**Comment by lucasborin** [comment]
Tested on SAP_BASIS 757/0000:
![image](https://user-images.githubusercontent.com/5233413/141111460-39cdb739-d837-4924-a6f6-4b040f6193f7.png)

There is a database dependency on the unit test that may be the root cause:
`SELECT SINGLE pname FROM tfdir INTO @DATA(function_group) WHERE fmode = 'R'.`

**Comment by ConjuringCoffee** [comment]
Looks like it checks the source code from the first remote function that is found in the database. For me, that's function group `/BSNAGT/SAPLF_DISPLAY_CONTENT`. Maybe the author had another function group for which it coincidentally worked.

**Comment by lucasborin** [comment]
Hm. In the sandbox system I use to develop code pal, it works:
![image](https://user-images.githubusercontent.com/5233413/141115801-654e0740-4027-442c-a728-756211497a54.png)

Yeah, again, I bet it is related to the database dependency.

**Comment by ConjuringCoffee** [comment]
Which function group is checked on your system?

**Comment by lucasborin** [comment]
I found the root cause. The test helper looks for an FG that has at least one FM with the RFC enabled, but the UT expects that the first FM from the FG is the one with the RFC enabled.
