### ISSUE TITLE
Incompatibility with abapGit after commit dc4b3705216757c7533f5802d51

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/code-pal-for-abap#528]
In abapGit, the variable `zif_abapgit_version=>gc_abap_version` was changed to `zif_abapgit_version=>c_abap_version`. 

This was done in commit [dc4b3705216757c7533f5802d51](https://github.com/abapGit/abapGit/commit/dc4b3705216757c7533f5802d51).
The change causes a syntax error in method `EXECUTE_GET_VERSIONS` in `Y_CODE_PAL_SERVICE`.

**Comment by ConjuringCoffee** [comment]
Will be made obsolete if dependency to abapGit is removed in #524

**Comment by lucasborin** [comment]
I'll turn it into a string to avoid external dependencies
