### ISSUE TITLE
Optional Parameters: Constructor

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#537]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
Y_CHECK_OPTIONAL_PARAMETERS

**Actual Behavior**
![image](https://user-images.githubusercontent.com/5233413/143930667-1b7b313b-7bf2-4fdb-82f9-b46adac622fa.png)

![image](https://user-images.githubusercontent.com/5233413/143930594-30b03f58-9902-4fae-9aa1-b774e9a82200.png)

**Expected Behavior**
Usually, optional parameters in the class constructor are welcome to inject test dependencies. Therefore, exempt it.

**Comment by D072189** [comment]
I cannot find any statement in the corresponding [style guide section](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#split-methods-instead-of-adding-optional-parameters) that makes an exception for constructors or dependency injection.

I think the "split methods" directive applies here, too: If you want to use dependency injection while adhering to the rule of avoiding optional parameters, offer one class method (e.g. `CREATE_WITH_DEFAULTS`) that takes no parameters and another (e.g. `CREATE_WITH_INJECTIONS`) that takes the injection parameters and make the constructor private with non-optional arguments. `CREATE_WITH_DEFAULTS` then creates the non-injected instances and passes them to the constructor, while `CREATE_WITH_INJECTIONS` just passes along its inputs.

**Comment by pokrakam** [comment]
I even prefer `LOCAL FRIENDS` definition of a test class over this kind of construct. Optional injectors to me expose test features in product code, and if they are needed for non-test features then we should be using factory classes or multiple factory methods.
