### ISSUE TITLE
Don't check abstract classes for interfaces

### ISSUE THREAD

**Issue by PeregrinTooc** [SAP/code-pal-for-abap#540]
**Check Name**
interface-in-class

**Actual Behavior**
check is applied for local abstract classes

**Expected Behavior**
Check should not be applied for abstract classes, especially not for local classes

**Comment by D072189** [comment]
The Clean ABAP guide [explicitly states](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#public-instance-methods-should-be-part-of-an-interface) that this rule should also apply to abstract classes, and links to [this](https://github.com/SAP/styleguides/blob/main/clean-abap/sub-sections/InterfacesVsAbstractClasses.md) longer discussion on the topic.
Hence, this is not a bug, but an intended feature. If you disagree with this style recommendation, you should open an issue over that the Clean ABAP repository.
