### ISSUE TITLE
code-pal, "a set of rules to guarantee the Clean ABAP adherence"

### ISSUE THREAD

**Issue by larshp** [SAP/code-pal-for-abap#541]
ref https://github.com/SAP/code-pal-for-abap/commit/0f34fa855d303de03f1191a2ec157cb45915ac06

"this tool contains a set of rules to guarantee the Clean ABAP adherence"

so reading this, it means that if the rules of code-pal is green, my code follows https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md ?

same with "based on Clean ABAP", this means all rules are based on Clean ABAP?

**Comment by lucasborin** [comment]
> so reading this, it means that if the rules of code-pal is green, my code follows https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md ?

Not at all, there are some rules we cannot guarantee via static checks. 

> same with "based on Clean ABAP", this means all rules are based on Clean ABAP?

IMO, yes, they are. Code Pal follows what is defined in the Clean ABAP style guide. Please, report if you find something going in the wrong direction. But yeah, as you mentioned, Code Pal does not guarantee that everything is covered. How about changing the word `guarantee`  to `support`?

`Based on the Clean ABAP, this tool contains a set of rules to support Clean ABAP adherence.`

**Comment by larshp** [comment]
"support" is good, its not misleading...

**Comment by larshp** [comment]
https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/number-methods.md
and
https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/message-translation.md
does not have links to the corresponding clean abap recommendation

**Comment by larshp** [comment]
so, the same misleading information now made it into https://blogs.sap.com/2022/05/05/how-to-enable-clean-code-checks-for-abap/
