### ISSUE TITLE
Method name check should consider prefixes 

### ISSUE THREAD

**Issue by suynwa** [SAP/code-pal-for-abap#546]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
Method Name Misleading for Boolean Return Check

**Actual Behavior**
The check reports a private method named _SHOULD_BOOKING_BE_DELETED

**Expected Behavior**
Developers use '_' prefix for private/protected methods. The check should consider this and report such method names

**Comment by D072189** [comment]
CodePAL implements the Clean ABAP style guide prescriptions. The Clean ABAP guide [explicitly](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#avoid-encodings-esp-hungarian-notation-and-prefixes) recommends not using any prefixes at all, so it is not a bug that we ignore prefixes here, it's a feature!
