### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#549]
The code references an interface which does not exist in a 7.50 system, thus causing a syntax error, and thus a short dump when the code inspector runs.

![image](https://user-images.githubusercontent.com/7078215/154380594-5d0614a2-fd0b-4a73-b229-2c557632f075.png)

**Comment by eugen-guenther-sap** [comment]
Thank you, i updated our Dependencies:
![image](https://user-images.githubusercontent.com/64586309/154429637-b4324f9b-f7b4-4f30-9bd2-9ceb03cdc2b5.png)

**Comment by abap-weasel** [comment]
Same issue as https://github.com/SAP/code-pal-for-abap/issues/548

**Comment by hardyp** [comment]
The problem is that the interface in question does not exist in 99.99999% of SAP customers systems, Thus it causes a syntax error, and hence a short dump. Thus the code is not as downward compatible as it might possibly be.
I "pulled" the latest version of the "Code Pal" this morning and it still references the interface that does not exist outside of internal SAP systems.
