### ISSUE TITLE
Cannot Pull into Z-Packages

### ISSUE THREAD

**Issue by abap-weasel** [SAP/code-pal-for-abap#55]
Installation Guide mentions to install Code Pal into local package, e.g. $CLEAN_CODE_MAIN. 
As I want to run tests in both DEV and QA stages, I wanted to use Z-package Z_CODE_PAL in DEV to be able to create transport request and import code pal to QA system.

It looks like Code Pal trys to use SAP Standard packages like CLEAN_CODE_FOUNDATION, which can be pulled into $-packages, but not into customer namespace. -- Please advise.

Import Log:

> Customer object DOMA YCICC_MESSAGE_KIND cannot be assigned to package CLEAN_CODE_FOUNDATION 
> 
> Import of object YCICC_MESSAGE_KIND failed 
> 
> Customer object DTEL YCICC_MESSAGE_KIND cannot be assigned to package CLEAN_CODE_FOUNDATION 
> 
> Import of object YCICC_MESSAGE_KIND failed 
> 
> Customer object DTEL YCICC_PRODUCTIVE_CODE cannot be assigned to package CLEAN_CODE_FOUNDATION 
> 
> Import of object YCICC_PRODUCTIVE_CODE failed 
> 
> Customer object DTEL YCICC_TESTCODE cannot be assigned to package CLEAN_CODE_FOUNDATION 
> 
> Import of object YCICC_TESTCODE failed 
> 
> Customer object DTEL YCICC_THRESHOLD cannot be assigned to package CLEAN_CODE_FOUNDATION 
> 
> Import of object YCICC_THRESHOLD failed 
> 
> Customer object TABL YTAB_EXEMPTIONS cannot be assigned to package CLEAN_CODE_FOUNDATION 
> 
> Import of object YTAB_EXEMPTIONS failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object YCX_ENTRY_NOT_FOUND failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object YCX_NO_CHECK_CUSTOMIZING failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object YCX_OBJECT_IS_EXEMPTED failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object YCX_OBJECT_NOT_PROCESSED failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_BASE failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_CALL_METHOD_USAGE failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_CATEGORY failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_CHECK_STMNT_POSITION failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_COMMENT_USAGE failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_CONSTANTS_INTERFACE failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_CYCLOMATIC_COMPLEXITY failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_DB_ACCESS_IN_UT failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_DECLARATION_IN_IF failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_DEPRECATED_KEY_WORDS failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_EMPTY_CATCHES failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_EMPTY_IF_BRANCHES failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_EMPTY_PROCEDURES failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_EQUALS_SIGN_CHAINING failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_FORM failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_FUNCTION failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_IS_INTERFACE_IN_CLASS failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_MAGIC_NUMBER failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_MAX_NESTING_DEPTH failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_METHOD_OUTPUT_PARAM failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_METHOD_RETURN_BOOL failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_NON_CLASS_EXCEPTION failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_NUMBER_ATTRIBUTES failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_NUMBER_EVENTS failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_NUMBER_INTERFACES failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_NUMBER_METHODS failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_NUM_EXEC_STATEMENTS failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_NUM_OUTPUT_PARAMETER failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_NUM_PUBLIC_ATTRIBUTES failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_RECEIVING_USAGE failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_SUB_ASSIGN_READ_TABLE failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CHECK_TEST_SEAM_USAGE failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_CLEAN_CODE_MANAGER failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_EXEMPTION_DISPATCHER failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_EXEMPTION_GENERAL failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_EXEMPTION_HANDLER failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_EXEMPTION_OF_CLASS failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_EXEMPTION_OF_FUNCTION_GROUP failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_EXEMPTION_OF_PROGRAM failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_MESSAGE_REGISTRATION failed 
> 
> Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_OBJECT_CREATION_DATE failed 
> 
> Error from SEO_INTERFACE_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_IF_CLEAN_CODE_MANAGER failed 
> 
> Error from SEO_INTERFACE_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_IF_EXEMPTION_DISPATCHER failed 
> 
> Error from SEO_INTERFACE_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_IF_EXEMPTION_OF_OBJECTS failed 
> 
> Error from SEO_INTERFACE_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_IF_OBJECT_CREATION_DATE failed 
> 
> Error from SEO_INTERFACE_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_IF_SCAN_MANAGER failed 
> 
> Error from SEO_INTERFACE_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_IF_SCAN_STATISTICS failed 
> 
> Error from SEO_INTERFACE_CREATE_COMPLETE. Subrc = 5 
> 
> Import of object Y_IF_TESTCODE_DETECTOR failed 
>

**Comment by larshp** [comment]
code-pal-for-abap uses FULL folder logic, https://docs.abapgit.org/ref-dot-abapgit.html#full, for which 

> The folder logic FULL forces the installation of a repository into packages with exactly the same name.

**Comment by lucasborin** [comment]
Changes are under development. You can check the `changing-from-full-to-prefix` branch.
