### ISSUE TITLE
quote comment alignment in empty CATCH block

### ISSUE THREAD

**Issue by jmg-sap** [SAP/code-pal-for-abap#550]
Hello, 

given the following code in which a CATCH block contains only a comment line …

```ABAP
    TRY.
        any_method( ).
      CATCH cx_any_exception.
        " comment
    ENDTRY.
```

… Code Pal raises the message "Quote comments indent along with the statements they comment!"

However, this is how the PrettyPrinter aligns the comment, and it is also where you would expect any content inside the CATCH block. Would Code Pal expect the comment to be aligned with ENDTRY?

(Yes, I know, you shouldn't have empty CATCH blocks, but that's a different story; maybe the comment explains exactly that!)

Kind regards,
Jörg-Michael

**Comment by D072189** [comment]
What version are you using? This should already be covered by [this line](https://github.com/SAP/code-pal-for-abap/blob/0a7da569041c83c57d172a0ce2f42c99334eae2c/src/checks/y_check_comment_position.clas.abap#L84), which was part of version 1.0.7. ([merge](https://github.com/SAP/code-pal-for-abap/pull/226))

**Comment by D072189** [comment]
No reproduction in current version.
