### ISSUE TITLE
Error from DDIF_TABLE_PUT

### ISSUE THREAD

**Issue by mainakaich** [SAP/code-pal-for-abap#566]
My SAP NW ABAP and BASIS version is Release 750 SP Level 0014. I have downloaded the .zip file for the version 1.16.3 of CodePAL from https://github.com/SAP/code-pal-for-abap. When I create the offline repository in ABAPGit and import the .zip file and then I pull the .zip file, I get the error below. 

![image](https://user-images.githubusercontent.com/54839961/179159117-dbf46d8b-22dc-4f60-9fac-ddc95005df03.png)

Please suggest how to resolve this. 
- Mainak

**Comment by larshp** [comment]
make sure you are running the latest abapGit version

try setting a breakpoint in function module `DDIF_TABLE_PUT` to check what the error is

**Comment by D072189** [comment]
Ctrl+F in the latest [abapGit build](https://raw.githubusercontent.com/abapGit/build/main/zabapgit.abap) does not find "error from DDIF_TABL_PUT" - all DDIF_TABL_PUT calls that fail should report a different error message (namely the sy-msg set by the failing DDIF_TABL_PUT). 

Please update your abapGit installation and see if the error changes to a more meaningful error or goes away.

**Comment by mainakaich** [comment]
Hello @larshp and @D072189,

Thanks so much, Installing the latest AbapGit solved the issue. 

Thanks,
Mainak
