### ISSUE TITLE
Code-Pal: number-executable-statements does not return any finding for a very big function module

### ISSUE THREAD

**Issue by SpringGong** [SAP/code-pal-for-abap#570]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). 

**Check Name**
> number-executable-statements

**Actual Behavior**
> In SAP internal system ISD, there is one function module Y_YFARR_RS_PROCESS_POB_01, which has around 2042 lines of code, and it has at least 1000 executable statements. But this Code-pal check does not return any findings.

The ABAP Code Pal class Y_CHECK_NUM_EXEC_STATEMENTS, method INSPECT_TOKENS does not return any finding for function module Y_YFARR_RS_PROCESS_POB_01, which has around 2042 lines of code.

I set breakpoint in the above mentioned check method, and found it just perform the check segment by segment, it will never calculate the total number of statements together.

**Expected Behavior**
> I expect the check should identify that this function module is too big.

Thanks and Best Wishes,
Spring

**Comment by D072189** [comment]
I cannot reproduce this issue with any of my own examples. Please check that:

1. You're running an up-to-date version of Code Pal
2. The function module is not older than any creation date threshold in the configuration of your check variant or profile
3. The threshold for the number of executable statement above which the check reports a finding is indeed set to something lower than the "1000" executable statements in this function module.

**Comment by SpringGong** [comment]
Hi Jüliger,

Thanks a lot for the info. Yes, our creation date threshold is on 01.01.2019, which is later than the creation date of my mentioned function module.

We will adjust the variant configuration in our system.

Thanks again and Best Wishes,
Spring
