### ISSUE TITLE
CodePal is not considering pragma ##CATCH_ALL for check Y_CHECK_CX_ROOT_USAGE

### ISSUE THREAD

**Issue by sachin-b-k** [SAP/code-pal-for-abap#573]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
> CX_ROOT Usage Check

**Actual Behavior**
> QATL reports the error "CX_ROOT should not be used!". In the description it instructs to use the pseudo comment “#EC NEED_CX_ROOT if necessary. But there is also a pragma ##CATCH_ALL. Why does QATL not consider the pragma?

**Expected Behavior**
> CodePal should also consider the pragma ##CATCH_ALL.

**Comment by D072189** [comment]
Code Inspector checks **cannot** support pragmas, see prior discussion in #337. 

In general, it is not recommended to run both the Extended Program Check and the equivalent Code Pal check - it's just redundant and leads to this pragma/pseudo comment confusion. Once the new documentation lands (#571), all checks that have SLIN (or other CI) equivalents will note this explicitly in their documentation.
