### ISSUE TITLE
Syntax errors in check classes

### ISSUE THREAD

**Issue by Holm2** [SAP/code-pal-for-abap#577]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
Y_CHECK_CALL_METHOD_USAGE
Y_CHECK_PREFER_LINE_EXISTS
Y_CHECK_PREFER_NEW_TO_CRT_OBJ

**Actual Behavior**
Since one of the latest updates the above mentioned check classes use non-existent methods or types which do not exist in the system (here: 7.50, SP23).
Syntax errors occur and no checks are executed.

`Y_CHECK_PREFER_LINE_EXISTS`
method `get_valid_last_token `and `get_valid_first_token` use unknown type `abap_boolean`

`Y_CHECK_CALL_METHOD_USAGE` and `Y_CHECK_PREFER_NEW_TO_CRT_OBJ`
method `get_code_with_exemption `and `get_code_with_issue `use unknown method `cl_abap_unit_assert=>skip`

**Expected Behavior**
Use another method/type.

**Comment by D072189** [comment]
Thanks for reporting this so quickly! The syntax errors should be gone now.

**Comment by Holm2** [comment]
Works well again, thank you
