### ISSUE TITLE
Too Many Output Parameters Check

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#58]
![image](https://user-images.githubusercontent.com/7078215/88788928-5c028980-d1d9-11ea-9c14-cd1a690861bd.png)

I get the error message abut too many output parameters.

But there is only one output parameter. The Pseudo-Comment to suppress the error does not work either.

![image](https://user-images.githubusercontent.com/7078215/88789106-a7b53300-d1d9-11ea-9e97-63f2f21a10c1.png)

**Comment by hardyp** [comment]
![image](https://user-images.githubusercontent.com/7078215/88789371-07abd980-d1da-11ea-8019-b2983f74094a.png)

This time there are NO output parameters at all!

![image](https://user-images.githubusercontent.com/7078215/88789478-1f835d80-d1da-11ea-9ce0-7c3b7e9df735.png)

**Comment by eugen-guenther-sap** [comment]
> ![image](https://user-images.githubusercontent.com/7078215/88788928-5c028980-d1d9-11ea-9c14-cd1a690861bd.png)
> 
> I get the error message abut too many output parameters.
> 
> But there is only one output parameter. The Pseudo-Comment to suppress the error does not work either.
> 
> ![image](https://user-images.githubusercontent.com/7078215/88789106-a7b53300-d1d9-11ea-9e97-63f2f21a10c1.png)

have you tried to place the pseudo comment after the RAISING ? 
See below:
```abap
METHODS: method_name RETURNING VALUE(result) TYPE REF TO cl_object
                    RAISING cx_exeption,                            "#EC NUM_OUTPUT_PARA
```

**Comment by eugen-guenther-sap** [comment]
> ![image](https://user-images.githubusercontent.com/7078215/88789371-07abd980-d1da-11ea-8019-b2983f74094a.png)
> 
> This time there are NO output parameters at all!
> 
> ![image](https://user-images.githubusercontent.com/7078215/88789478-1f835d80-d1da-11ea-9ce0-7c3b7e9df735.png)

CHANGING is an output parameter because the related variable can be changed and is therefore both an import and an export parameter.

**Comment by eugen-guenther-sap** [comment]
Anyway it should not be triggering with just one variable.

**Comment by eugen-guenther-sap** [comment]
Can you please check the date you updated the class Y_CHECK_METHOD_OUTPUT_PARAM?
The class should be updated after June 25th, 2020.

Due to the individual changes you made, it may be an old version.

**Comment by hardyp** [comment]
I have ABAPGIT set up to run a batch job every night and automatically update several repositories, including the "Code Pal" one. I have made no changes to any of the classes. That is a wonderful feature of abapGit. The last update to Y_CHECK_METHOD_OUTPUT_PARAM was on 03/07/2020.

**Comment by eugen-guenther-sap** [comment]
Thank you, it should be solved now :)

**Comment by hardyp** [comment]
I just downloaded the latest version from Github. Now it has a syntax error.

![image](https://user-images.githubusercontent.com/7078215/89263749-22b49880-d675-11ea-8636-2bc82d0e05fc.png)

**Comment by eugen-guenther-sap** [comment]
has your system the type: `string_table`?

**Comment by hardyp** [comment]
Yes it does ... I am on ECC 6.0 EHP6, ABAP 750 by the way.

I just checked in a 7.52 system - STRING255_TAB does not exist there either. It must have been created in a really high vesrion of ABAP no-one outside SAP uses as yet.

**Comment by eugen-guenther-sap** [comment]
and now?

**Comment by hardyp** [comment]
There is no short dump anymore.

The warning now does not appear for only one output parameter, only when two or more, which I presume is the idea.

If that is the case, this issue can be closed.

Cheersy Cheers

Paul
