### ISSUE TITLE
IF 1 = 2. endif. statement?

### ISSUE THREAD

**Issue by krausege** [SAP/code-pal-for-abap#583]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
> Cyclomatic Complexity

**Actual Behavior**
- system: EHR, client 001
- 
- Class CL_HRPAYNL_WCR_UPDATE_DATA Method PREP_SET_CC_ADD_MESSAGE Row 1 Column 2
==> this statement is counted in the cyclomatic complexity as it is just for navigation purposes :
**IF 1 = 2. MESSAGE i013(hrpaynl_wcr_en) WITH iv_juper iv_for_year INTO mv_dummy. ENDIF.**

**Expected Behavior**
> Do not count this in the cyclomatic complexity as it is not functional

**Comment by krausege** [comment]
![image](https://user-images.githubusercontent.com/22143949/199933017-5aba5427-c4f8-4665-aa96-a7176246a76d.png)

**Comment by bjoern-jueliger-sap** [comment]
Cyclomatic complexity does not care whether the branches it finds can realistically be executed. If a branch formally exists, it will be counted.

Also, this strange pattern of guarding messages by tautologically false conditions is not recommended. See [the style guide](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#make-messages-easy-to-find) for alternatives.

**Comment by krausege** [comment]
Hello Bjoern,
thank you for your reply and advice!
yes you are right. The work around to install the forward navigation is not the best one and it violates the style guide. I will either suppress the error with a pseudo comment or remove the "forward navigation" forcing the opening of se91 separately.
Best regards, Gernot
