### ISSUE TITLE
Comment Usage: structural elements are counted. Ok?

### ISSUE THREAD

**Issue by krausege** [SAP/code-pal-for-abap#584]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
> Comment Usage

**Actual Behavior**
> System EHR client 001
> Class CL_HRPAYNL_WCR_READ_CUSTOMIZNG Row 24 Column 0 / method READ_ALL_JUPERS_ALL_FOR_YEARS
the counting of these comment lines eventually can be skipped?
**********************************************************************************
they are just there to improve the readability of the code and do not contain any replicated meaning that
could be expressed in the codelines.

**Expected Behavior**
> Do not count the comment lines that are used to structure extended comments

**Comment by krausege** [comment]
![image](https://user-images.githubusercontent.com/22143949/199932542-eb384e61-c766-46e4-a059-6890b29bf983.png)

**Comment by bjoern-jueliger-sap** [comment]
Why should they be skipped? The check says that it counts the number of comments - if it didn't count all comments, it would not do what it says it does. 

Please be mindful of the [check documentation](https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/comment-usage.md):

> Perhaps there is no issue and every comment in the code is actually meaningful and necessary. Do not treat findings from this check as issues that need to be "solved" by deleting potentially valuable comments, but consider them an invitation to think about your comment practices and find ways to incorporate the information they convey directly into the code itself.

If you're treating findings from this check as issues that **need** to be solved, you're doing it wrong.

**Comment by krausege** [comment]
Hello Bjoern,
thank you for your reply!!
it was an idea of a colleague and me. We saw some potential to improve the clean code initiative. From your reply
I see that there is not much flexibility. The lines are counted. That is it. As suggested by you we will ignore the warnings.
Best regards, Gernot
