### ISSUE TITLE
Link to "Github Documentation" in the code pal finding on Eclipse ends in a "404 page not found" error

### ISSUE THREAD

**Issue by BaerbelW** [SAP/code-pal-for-abap#585]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
> All the ones I spot checked when trying out the code pal checks from Eclipse (V2022-12).

**Actual Behavior**
> Clicking on the available link to the [Github documentation](https://github.com/SAP/code-pal-for-abap/blob/master/docs/check%20s/comment-usage.md) - random example - ends with the "404 This is not the page you are looking for" error when done from Eclipse (when clicked from the ATC result browser in the GUI, the link opens properly)

**Expected Behavior**
> The link should point to https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/comment-usage.md (eliminating the "%20" from the "/check**%20**s/" part of the link is enough to make it work for me).

Thanks for looking into this!

Cheers
Bärbel

**Comment by bjoern-jueliger-sap** [comment]
I cannot reproduce this with my ADT installation in a SAP_BASIS 7.57 system - there is no space in the link for me and the link works fine. 

What SAP_BASIS release does your backend have?

**Comment by BaerbelW** [comment]
We are on SAP_BASIS 7.50 SP25 EHP8.

**Comment by bjoern-jueliger-sap** [comment]
This is a bug in standard SAP code, not in CodePal: SAP_BASIS 7.50 indeed reproducibly generates a space into the URL for no discernible reason. I'll try to get this fixed.

**Comment by BaerbelW** [comment]
@bjoern-jueliger-sap 
Hi Björn,

if this is a bug in standard SAP code, do I need to do something like raise an OSS incident? As mentioned above, the "space" is only inserted in Eclipse. The link works when following it from the NW750 system.

Cheers
Bärbel

**Comment by bjoern-jueliger-sap** [comment]
Hi Bärbel,

I've addressed this via internal SAP channels, at the moment I don't think you need to raise an OSS incident. I'll update this issue when I have more information or when a solution is available.

And yes, the space is only there in Eclipse, the reason for this is that the way CodePal manages to get the link into the ADT docu display is rather convoluted and involves a conversion from SAPScript to HMTL at one point; this conversion seems to behave differently in 7.50 than in the higher releases I tested and produces this space. It might turn out this isn't a bug and/or that there's a workaround we could implement on CodePal side.

**Comment by bjoern-jueliger-sap** [comment]
The problem apparently affects SAP_BASIS 7.50 to 7.53. Installation of note [3313518](https://launchpad.support.sap.com/#/notes/3313518) should solve the problem, no action from CodePal side required.
