### ISSUE TITLE
CodePal shows issues for other objects used in the object checked

### ISSUE THREAD

**Issue by sachin-b-k** [SAP/code-pal-for-abap#590]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
> NonLocal Nested Reading DB OP (SELECT) found.
> Cyclomatic complexity must be lower than 10! (12>=10)
> 1 public methods without interface!
> Possible sequential read on a sorted table
> Sequential DELETE-statement on STANDARD table inside LOOP ... ENDLOOP; nesting level 1

**Actual Behavior**
> The error "NonLocal Nested Reading DB OP (SELECT) found" is only in a object(BUPA_PADR_ALLOWED_GET) which is called in the class "CL_BUPA_ECC_CU_PRTNR_FNCT_MAP". When Code Pal check is executed during QATL, it is showing this issue which is actually in FM "BUPA_PADR_ALLOWED_GET".

**Expected Behavior**
> The issues only in the class CL_BUPA_ECC_CU_PRTNR_FNCT_MAP should be shown and not for the objects which is called in the class.
![2370060588_codepal check](https://user-images.githubusercontent.com/110591615/236384512-7a382b78-bed7-49cf-86f9-af4eee5f1786.png)

**Comment by bjoern-jueliger-sap** [comment]
This is not a CodePal issue, the message "NoneLocal Nested DB OP" is emitted by standard SAP check CL_CI_TEST_DB_OPS_IN_LOOPS. 

Also, that check is explicitly a cross-program check intended to find DB operations inside of called modularization units and so findings "outside" the checked object are intended. If you don't want cross-program results, don't run cross-program checks.
