### ISSUE TITLE
[Assign a Nested Table] Check should ignore test classes

### ISSUE THREAD

**Issue by MatthiasABC** [SAP/code-pal-for-abap#592]
**Check Name**
Assign a Nested Table

**Actual Behavior**
The current check reports when a nested table is assigned (using '=', MOVE etc.). This can lead to the copying of larger amounts of data and could have negative performance impact. Code Pal reports this a finding which can be hidden with "#EC CI_CONV_OK

This also applies to methods with RETURNING parameters as they are returned by value. For unit tests, we are most of the times only testing with a few records, so the amount of   data will be very small and the performance will be okay.
  
However, the [Style guide](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#returning-large-tables-is-usually-okay) says that RETURNING large tables is usually okay. There, it is actually pointed out that performance problems can hardly be observed as kernel optimizations improved the RETURNING performance.

Using EXPORTING parameters by reference make the code unnecessary longer than RETURNING parameter.

**Expected Behavior**
If there are no more performance issue because of the kernel optimization, the check should be removed.
And in general, for test classes, the check should be deactivated, as the coding will not be better readable with EXPORTING parameters.

**Comment by obr-sap** [comment]
I'd like to second this request and even go so far as to propose that the check is **dropped** also for _productive code_.

Complying with the _clean-code guideline_ should **not** incur _pragmas_.

**Comment by bjoern-jueliger-sap** [comment]
This is not a CodePal issue, the messages that can be suppressed with CI_CONV_OK are emitted by the SAP standard check CL_CI_TEST_MOVE_PERFORMANCE. The check is not related to Clean ABAP at all. If you have issues with this check's behavior, you should open an SAP support ticket on application component BC-ABA-LA.

@obr-sap If you don't want to run a check on productive code you can just not execute it? Which checks you run is up to you, and if you think any specific check is completely pointless, then you can just not make it part of your check variant.

**Comment by obr-sap** [comment]
@bjoern-jueliger-sap Alas, the engineering teams are often not the ones who define the check scope. But your point about this not coming from code pal is noted. Thanks!

**Comment by MatthiasABC** [comment]
When executing transaction ATC with variant Y_CODE_PAL, as well when the automatic QATL checks run before releasing an ABAP Transport, these findings are reported as Prio 3, Code Pal. In the details, the check class CL_CI_TEST_MOVE_PERFORMANCE is mentioned. Therefore this looks like coming from Code Pal and has the corresponding Check Title, so it cannot be easily detected why it should not by a Code Pal issue.

Besides that it is also mentioned in the [Style guide](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#returning-large-tables-is-usually-okay). And as stated there, a solution by replacing a RETURNING parameter with EXPORTING leads to needlessly longer code, which is no clean code.

**Comment by bjoern-jueliger-sap** [comment]
Y_CODE_PAL is not the name of any check variant delivered by this repository, it's just a variant someone in your system created. If it contains the check CL_CI_TEST_MOVE_PERFORMANCE, then the name is badly chosen and obviously does not contain only CodePal checks. You need to talk to whoever configures the quality measures in your development environment about this.
