### ISSUE TITLE
Missing implementation for rule Use assert class instead of ASSERT

### ISSUE THREAD

**Issue by larshp** [SAP/code-pal-for-abap#593]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

Looks like the check for https://github.com/SAP/abap-cleaner/blob/main/docs/rules/AssertClassRule.md is missing?

**Comment by bjoern-jueliger-sap** [comment]
I can't find any corresponding rule in the [style guide](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md) that demands that one should replace ASSERTs by calls to an application-specific class.

Personally I agree ASSERTs are bad, but it is not clear to me what the benefit of the "assert class" here is. If it's just a static class and the implementation of the methods themselves just uses ASSERT, I don't see any advantage in using it.

I could be convinced that, if there was an *interface* for these assertions and the assert methods were instance methods on that interface, this would be useful to implement something like a strategy pattern to use different kinds of "asserts" in different contexts there (e.g. ASSERT in test environment and write a log in productive environments). But the ABAP Cleaner example writes `cx_assert=>...` as static methods so apparently this is not the intention here, so what is this rule actually for?

**Comment by larshp** [comment]
okay, thanks, closing
