### ISSUE TITLE
Broken links to GitHub documentation in long texts

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/code-pal-for-abap#594]
Each check has a long text that contains a link to the GitHub documentation. Unfortunately, all links are broken for me. It looks like there's an erroneous space character in the folder name, leading to `check%20s` instead of `checks`.

![image](https://github.com/SAP/code-pal-for-abap/assets/72548231/2f8d3e84-f819-4c1c-b2ca-06f19f878fcf)

- Actual: https://github.com/SAP/code–pal–for–abap/blob/master/docs/check%20s/function–routine.md
- Expected: https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/function-routine.md

This seems to be a general problem, not just for this single check.

**Comment by ConjuringCoffee** [comment]
I'd have expected the problem to be the constant definition `c_docs_path-checks` in `Y_CHECK_BASE`, but that isn't it.

**Comment by bjoern-jueliger-sap** [comment]
This is a [known problem](https://github.com/SAP/code-pal-for-abap/issues/585), please install SAP note [3313518](https://launchpad.support.sap.com/#/notes/3313518) to fix it.

**Comment by ConjuringCoffee** [comment]
Thanks for the quick reply, Björn. What do you think about including this in a new section on "Known issues" in the documentation? I could submit a pull request if you like.

**Comment by bjoern-jueliger-sap** [comment]
> Thanks for the quick reply, Björn. What do you think about including this in a new section on "Known issues" in the documentation? I could submit a pull request if you like.

Good idea! If you want to do that, it would be very welcome.
