### ISSUE TITLE
Pseudo-Comments not suppressing warnings

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#6]
I have tried to suppress the two warning by using the psuedo-comment suggested:-

![image](https://user-images.githubusercontent.com/7078215/81139887-bf9a6380-8faa-11ea-84fb-0528982fbd15.png)

However they still comes up as warnings even I back right out of the class and go back in again.

![image](https://user-images.githubusercontent.com/7078215/81139931-e789c700-8faa-11ea-8860-5a49aea03bb2.png)

However the pseudo comment works in other methods in the class - there the warning is indeed suppressed.

**Comment by maxim-engel-sap** [comment]
Hi Paul, thank you for the comment.
The right pseudo-comment is `"#EC CHECK_POSITION`
For all checks `#EC ` as prefix and then the pseudo-comment suggested (`CHECK_POSITION` in this case)
Since I see a different pseudo-comment in your screenshot, this might be the issue here.

**Comment by hardyp** [comment]
I wondered about that. In the standard SAP ATC checks the little box says to use a comment starting with #EC but not the new "Y" ones. Anyway I added the EC# to the front of the comments in that method and the warnings went away.

But this one still appears as a warning.

![image](https://user-images.githubusercontent.com/7078215/81151465-5c1d2f80-8fc4-11ea-844e-dbac0bda6b96.png)

![image](https://user-images.githubusercontent.com/7078215/81151540-6fc89600-8fc4-11ea-9c93-196c9e848ff0.png)

and this method is not highlighted...

![image](https://user-images.githubusercontent.com/7078215/81151744-a0103480-8fc4-11ea-8393-145e16378e5f.png)

I take the comment out, the warning comes back

and now I cannot suppress the warning any more even using "#EC CHECK POSITION.

**Comment by hardyp** [comment]
I can see the pattern. In the below method I got a warning when there was no comment until I added the incorrect comment. Now it does not show up any more as a warning.

![image](https://user-images.githubusercontent.com/7078215/81156464-50803780-8fc9-11ea-879e-952a5dd269f1.png)

If I take that comment out the warning will come back. After that point I will never be able to suppress the warning no matter what I do.

**Comment by eugen-guenther-sap** [comment]
you need to write `"#EC CHECK_POSITION`  with `_`

**Comment by hardyp** [comment]
OK that worked.

The only remaining puzzle is why the method above (VALIDATE_RECURSIVE_LINKS) does not show up on the new check. The CHECK statement is not on the first line, and has no valid pseudo comment, so it should show up.

After some tests the answer is clear - one does not need the EC# at the start. The comment CHECK_POSITION just on its own works fine. But I suppose one puts the EC# in just to show it is a pseudo comment.

Given that fact I can close this issue.
