### ISSUE TITLE
Proo

### ISSUE THREAD

**Issue by MacUp22** [SAP/code-pal-for-abap#606]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
> Use this section to identify the affected Check.

**Actual Behavior**
> Use this section to describe what is wrong.

**Expected Behavior**
> Use this section to describe what do you expect.

**Comment by bjoern-jueliger-sap** [comment]
You seem to have submitted the bug report template without any changes.
