### ISSUE TITLE
Check Y_CHECK_PREFER_IS_NOT is not checking ASSERT conditions

### ISSUE THREAD

**Issue by larsip** [SAP/code-pal-for-abap#610]
Hallo,

we are using check Y_CHECK_PREFER_IS_NOT and it is not checking ASSERT condition.
**Check Name**
> Y_CHECK_PREFER_IS_NOT

**Actual Behavior**
> When checking code:
REPORT Y_TEST_PREFER_IS_NOT_ASSERT.
data: lv_value.
START-OF-SELECTION.  
if not lv_value is INITIAL.
    write 'test'.
endif.  
assert not lv_value is INITIAL.

the first "if" part is reported as a finding but not the "assert" part.

**Expected Behavior**
> I would expect that both was found.
I think the issue is that in the constructor for check the relevant statement types are set to 'if' and then the 'assert' is not checked. (relevant_statement_types = VALUE #( ( scan_struc_stmnt_type-if ) ).
I have tried to remove the statement together with the following statement _relevant_structure_types = VALUE #(  )._ and now both the if and the assert is reported as finding.

**Comment by vishalcmahajan-git** [comment]
Update the relevant_statement_types to include both:
relevant_statement_types = VALUE #( ( scan_struc_stmnt_type-if ) ( **scan_struc_stmnt_type-assert** ) ).

This change should ensure that both the “if” and the “assert” parts are checked by the Y_CHECK_PREFER_IS_NOT rule. Let me know if this works
