### ISSUE TITLE
Link "Github documentation" in check result doesn't work

### ISSUE THREAD

**Issue by FrankBerwanger** [SAP/code-pal-for-abap#617]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
> Seems to span all checks

**Actual Behavior**
> When using the link in the check result "Github documentation", I get a 404 because there is a blank in the URL check%20 instead of checks.

**Expected Behavior**
> pages is found

**Comment by bjoern-jueliger-sap** [comment]
Please install note [3313518](https://me.sap.com/notes/3313518) to fix this, cf. also [known issues](https://github.com/SAP/code-pal-for-abap/blob/master/pages/known-issues.md).
