### ISSUE TITLE
[Y_CHECK_NUM_OUTPUT_PARAMETER] Not able to set threshold

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#68]
![image](https://user-images.githubusercontent.com/5233413/90437812-5944d700-e0a9-11ea-92bf-89600ce96942.png)

The threshold is locked.

**Comment by lucasborin** [comment]
@eugen-guenther-sap: From my perspective, we should enable it. What do you think?

**Comment by eugen-guenther-sap** [comment]
this is a styleguide clean code check, the threshold will be always the same, at least for us.
