### ISSUE TITLE
When you need a class never use local classes (within classes, reports, function groups, ...)

### ISSUE THREAD

**Issue by eugen-guenther-sap** [SAP/code-pal-for-abap#78]
except for unit tests

**Comment by ThomasKempfle** [comment]
Why? This feature is neither deprecated, nor in contrast to Clean Code!

Creating global objects always comes to a price: 
> Other developers might use it without asking first
> You will expose (potentially dangerous) logics to a wider scope you have originally estimated
> You will have to think about global naming guide lines in order to make things distinguishable and other rules

For similar reasons, global attributes should generally be avoided in development objects...

When I started doing OO in SAP I created everything as a public class, but changed my mind over the years.

AND: Test classes are ALWAYS local!!!!
