### ISSUE TITLE
Changing SCI - Cancel attributes popup

### ISSUE THREAD

**Issue by jrodriguez-rc** [SAP/code-pal-for-abap#8]
You save attributes for a check, then access them again to review:
![image](https://user-images.githubusercontent.com/56556686/81162673-dd0d0480-8f8d-11ea-995e-36f07d7d2750.png)

Then close (or cancel), the saved values are removed:
![image](https://user-images.githubusercontent.com/56556686/81162715-ebf3b700-8f8d-11ea-8d33-ca68eb7aa373.png)

**Comment by eugen-guenther-sap** [comment]
Thank you, i have fixed it.
