### ISSUE TITLE
New check class for unit test coverage

### ISSUE THREAD

**Issue by ThomasKempfle** [SAP/code-pal-for-abap#83]
Dear Code Pal team,

I developed a new custom SCI/ATC check class for SAP Release 754, that I would like to contribute to the Code Pal project. Unfortunately, I noticed, that the Code Pal seems to be protected in GitHub, hence I am not allowed to upload my check class. 

My check class determines the ABAP unit test coverage of any given set of ABAP sources defined in the SCI/ATC. It does it in this way:
1. Determine the cyclomatic complexity of a class/Fugr/program. If the complexity exceeds a customizable threshold, proceed with step 2. (This is relevant, since I do not want developers to produce unit tests for boiler plate code or SETer/GETer methods).
2. Search for unit tests for these development object.
3. Execute the unit tests
4. Retrieve the (line based) coverage of the executed unit tests.
5. If the unit test coverage in % falls below a customizable value (default 60%), this will produce a warning message in SCI/ATC. An error message will be issued, if the coverage falls below a second customizable value (default 20%) or the development object has no unit tests.

If you do think, this is a helpfull check and should be part of the Code Pal, please advise, how I can contribute.

Regards 

Thomas

**Comment by estevao-schultz-neto-SAP** [comment]
Dear Thomas! 

Thank you very much for your cooperation. The CHECK seems to be very interesting. We will evaluate it in short and find a way out for you to post/stage the objects.

yours,
code pal for ABAP Team

**Comment by lucasborin** [comment]
Dear Thomas,

You have already forked the repository. Now, you have first to commit your changes to your forked repository and then create a pull-request to the main base repository. Could you please try it?

Regards,
Lucas

**Comment by ThomasKempfle** [comment]
For some reasons, I am not allowed to create a branch from the development. When using the ABAPGit client I will receive a message 403. When using the Github desktop application, I will receive a message "It looks like you don't have write access to sap/code-pal-for-abap." Are you sure, this project is open for foreign change?

**Comment by lucasborin** [comment]
Are you working on your forked version instead of the main base? 

Forking the main repository, as you did, will allow you to commit and push your new changes to the forked version only. Then, when you finish your development, you can create a pull-request from your forked version to the main repository.

Your forked version:
> https://github.com/ThomasKempfle/code-pal-for-abap.git

Main base repository:
> https://github.com/SAP/code-pal-for-abap

**Comment by lucasborin** [comment]
By the way, if you try to make a change in the `master` or `dev` directly, Github will automatically create a fork of the project with a new branch. So, you will be able to create a pull-request to the main repository as we are recommending. 

Github Message:
![image](https://user-images.githubusercontent.com/5233413/91327512-fdaad580-e79b-11ea-9730-cee122f16b3f.png)

**Comment by ThomasKempfle** [comment]
When I follow your description, I do not have a branch "nightly", hence I cannot continue to step 3.

**Comment by lucasborin** [comment]
Hm, I see. We decided to deprecate the "nightly" branch because the name was confusing. 
Now, you can use the `dev` branch from your forked repository to create a pull-request the main repository.

By the way, have you staged your new check on the abapGit? 
I haven't found it in your forked repository. 

Besides, you will have to update your dev branch. You can do it on the following URL:
https://github.com/ThomasKempfle/code-pal-for-abap/compare/dev...SAP:dev

If you need any additional support, please, let me know.

**Comment by eugen-guenther-sap** [comment]
> Dear Code Pal team,
> 
> I developed a new custom SCI/ATC check class for SAP Release 754, that I would like to contribute to the Code Pal project. Unfortunately, I noticed, that the Code Pal seems to be protected in GitHub, hence I am not allowed to upload my check class.
> 
> My check class determines the ABAP unit test coverage of any given set of ABAP sources defined in the SCI/ATC. It does it in this way:
> 
> 1. Determine the cyclomatic complexity of a class/Fugr/program. If the complexity exceeds a customizable threshold, proceed with step 2. (This is relevant, since I do not want developers to produce unit tests for boiler plate code or SETer/GETer methods).
> 2. Search for unit tests for these development object.
> 3. Execute the unit tests
> 4. Retrieve the (line based) coverage of the executed unit tests.
> 5. If the unit test coverage in % falls below a customizable value (default 60%), this will produce a warning message in SCI/ATC. An error message will be issued, if the coverage falls below a second customizable value (default 20%) or the development object has no unit tests.
> 
> If you do think, this is a helpfull check and should be part of the Code Pal, please advise, how I can contribute.
> 
> Regards
> 
> Thomas

1. Why cyclomatic complexity? We have a check that is already doing that.
(maybe excluding methods that are starting with get & set would do the same?)

4. Do you meant the statement coverage? 

5. Maybe it would be better when there is youst one threshold per check?

**Comment by estevao-schultz-neto-SAP** [comment]
Hello Thomas,  

we just would like to understand what was your requirements for having the cyclomatic complexity attached to the coverage (we assume statements coverage) ? Any special need for that?

Besides that, we think the check itself about the coverage is a very good idea. Especially if we provide it with a customizable Threshold which the users could couple with their own Target/KPI. 

Beforehand, thank you very much for your contribution!
code pal for abap team

**Comment by eugen-guenther-sap** [comment]
the check needs a lot of rework, because it is not compatible with it code pal checks.
I closed the pull request.

But we like the idea of a statement coverage check and will inplement it in the near future.
